### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache
  commentId: N:OpenQA.Selenium.DevTools.V85.ApplicationCache
  id: OpenQA.Selenium.DevTools.V85.ApplicationCache
  children:
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCache
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheAdapter
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheResource
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheStatusUpdatedEventArgs
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandResponse
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandSettings
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.FrameWithManifest
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandResponse
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandSettings
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandResponse
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandSettings
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandResponse
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandSettings
  - OpenQA.Selenium.DevTools.V85.ApplicationCache.NetworkStateUpdatedEventArgs
  langs:
  - csharp
  - vb
  name: OpenQA.Selenium.DevTools.V85.ApplicationCache
  nameWithType: OpenQA.Selenium.DevTools.V85.ApplicationCache
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache
  type: Namespace
  assemblies:
  - WebDriver
references:
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCache
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCache
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCache.html
  name: ApplicationCache
  nameWithType: ApplicationCache
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCache
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheAdapter
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheAdapter
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheAdapter.html
  name: ApplicationCacheAdapter
  nameWithType: ApplicationCacheAdapter
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheAdapter
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheResource
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheResource
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheResource.html
  name: ApplicationCacheResource
  nameWithType: ApplicationCacheResource
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheResource
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheStatusUpdatedEventArgs
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheStatusUpdatedEventArgs
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheStatusUpdatedEventArgs.html
  name: ApplicationCacheStatusUpdatedEventArgs
  nameWithType: ApplicationCacheStatusUpdatedEventArgs
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.ApplicationCacheStatusUpdatedEventArgs
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandSettings
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandSettings.html
  name: EnableCommandSettings
  nameWithType: EnableCommandSettings
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandSettings
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandResponse
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandResponse.html
  name: EnableCommandResponse
  nameWithType: EnableCommandResponse
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.EnableCommandResponse
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.FrameWithManifest
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.FrameWithManifest
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.FrameWithManifest.html
  name: FrameWithManifest
  nameWithType: FrameWithManifest
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.FrameWithManifest
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandSettings
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandSettings.html
  name: GetApplicationCacheForFrameCommandSettings
  nameWithType: GetApplicationCacheForFrameCommandSettings
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandSettings
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandResponse
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandResponse.html
  name: GetApplicationCacheForFrameCommandResponse
  nameWithType: GetApplicationCacheForFrameCommandResponse
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetApplicationCacheForFrameCommandResponse
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandSettings
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandSettings.html
  name: GetFramesWithManifestsCommandSettings
  nameWithType: GetFramesWithManifestsCommandSettings
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandSettings
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandResponse
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandResponse.html
  name: GetFramesWithManifestsCommandResponse
  nameWithType: GetFramesWithManifestsCommandResponse
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetFramesWithManifestsCommandResponse
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandSettings
  parent: OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandSettings.html
  name: GetManifestForFrameCommandSettings
  nameWithType: GetManifestForFrameCommandSettings
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandSettings
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandResponse
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandResponse.html
  name: GetManifestForFrameCommandResponse
  nameWithType: GetManifestForFrameCommandResponse
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.GetManifestForFrameCommandResponse
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache.NetworkStateUpdatedEventArgs
  commentId: T:OpenQA.Selenium.DevTools.V85.ApplicationCache.NetworkStateUpdatedEventArgs
  href: OpenQA.Selenium.DevTools.V85.ApplicationCache.NetworkStateUpdatedEventArgs.html
  name: NetworkStateUpdatedEventArgs
  nameWithType: NetworkStateUpdatedEventArgs
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache.NetworkStateUpdatedEventArgs
- uid: OpenQA.Selenium.DevTools.V85.ApplicationCache
  commentId: N:OpenQA.Selenium.DevTools.V85.ApplicationCache
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V85.ApplicationCache
  nameWithType: OpenQA.Selenium.DevTools.V85.ApplicationCache
  fullName: OpenQA.Selenium.DevTools.V85.ApplicationCache
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85
    name: V85
    href: OpenQA.Selenium.DevTools.V85.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85.ApplicationCache
    name: ApplicationCache
    href: OpenQA.Selenium.DevTools.V85.ApplicationCache.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85
    name: V85
    href: OpenQA.Selenium.DevTools.V85.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85.ApplicationCache
    name: ApplicationCache
    href: OpenQA.Selenium.DevTools.V85.ApplicationCache.html
