### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  id: InitiatorTypeValues
  parent: OpenQA.Selenium.DevTools.V85.Network
  children:
  - OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Other
  - OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Parser
  - OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Preload
  - OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Script
  - OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.SignedExchange
  langs:
  - csharp
  - vb
  name: InitiatorTypeValues
  nameWithType: InitiatorTypeValues
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: InitiatorTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 10
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated values for Network.Initiator.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum InitiatorTypeValues
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum InitiatorTypeValues
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Parser
  commentId: F:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Parser
  id: Parser
  parent: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  langs:
  - csharp
  - vb
  name: Parser
  nameWithType: InitiatorTypeValues.Parser
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Parser
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Parser
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 16
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated member for the parser value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "parser")]

      Parser = 0
    return:
      type: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
    content.vb: >-
      <EnumMember(Value:="parser")>

      Parser = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: parser
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Script
  commentId: F:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Script
  id: Script
  parent: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  langs:
  - csharp
  - vb
  name: Script
  nameWithType: InitiatorTypeValues.Script
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Script
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Script
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 21
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated member for the script value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "script")]

      Script = 1
    return:
      type: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
    content.vb: >-
      <EnumMember(Value:="script")>

      Script = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: script
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Preload
  commentId: F:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Preload
  id: Preload
  parent: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  langs:
  - csharp
  - vb
  name: Preload
  nameWithType: InitiatorTypeValues.Preload
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Preload
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Preload
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 26
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated member for the preload value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "preload")]

      Preload = 2
    return:
      type: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
    content.vb: >-
      <EnumMember(Value:="preload")>

      Preload = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: preload
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.SignedExchange
  commentId: F:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.SignedExchange
  id: SignedExchange
  parent: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  langs:
  - csharp
  - vb
  name: SignedExchange
  nameWithType: InitiatorTypeValues.SignedExchange
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.SignedExchange
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: SignedExchange
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 31
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated member for the SignedExchange value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "SignedExchange")]

      SignedExchange = 3
    return:
      type: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
    content.vb: >-
      <EnumMember(Value:="SignedExchange")>

      SignedExchange = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: SignedExchange
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Other
  commentId: F:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Other
  id: Other
  parent: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  langs:
  - csharp
  - vb
  name: Other
  nameWithType: InitiatorTypeValues.Other
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.Other
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Other
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v85/Network/InitiatorTypeValues.cs
    startLine: 36
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V85.Network
  summary: Enumerated member for the other value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "other")]

      Other = 4
    return:
      type: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
    content.vb: >-
      <EnumMember(Value:="other")>

      Other = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: other
references:
- uid: OpenQA.Selenium.DevTools.V85.Network
  commentId: N:OpenQA.Selenium.DevTools.V85.Network
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V85.Network
  nameWithType: OpenQA.Selenium.DevTools.V85.Network
  fullName: OpenQA.Selenium.DevTools.V85.Network
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85
    name: V85
    href: OpenQA.Selenium.DevTools.V85.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85.Network
    name: Network
    href: OpenQA.Selenium.DevTools.V85.Network.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85
    name: V85
    href: OpenQA.Selenium.DevTools.V85.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V85.Network
    name: Network
    href: OpenQA.Selenium.DevTools.V85.Network.html
- uid: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
  parent: OpenQA.Selenium.DevTools.V85.Network
  href: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues.html
  name: InitiatorTypeValues
  nameWithType: InitiatorTypeValues
  fullName: OpenQA.Selenium.DevTools.V85.Network.InitiatorTypeValues
