### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  commentId: T:OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  id: AttributionReportingSourceRegistrationTimeConfig
  parent: OpenQA.Selenium.DevTools.V125.Storage
  children:
  - OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Exclude
  - OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Include
  langs:
  - csharp
  - vb
  name: AttributionReportingSourceRegistrationTimeConfig
  nameWithType: AttributionReportingSourceRegistrationTimeConfig
  fullName: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: AttributionReportingSourceRegistrationTimeConfig
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
    startLine: 10
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V125.Storage
  summary: AttributionReportingSourceRegistrationTimeConfig
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum AttributionReportingSourceRegistrationTimeConfig
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum AttributionReportingSourceRegistrationTimeConfig
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
- uid: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Include
  commentId: F:OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Include
  id: Include
  parent: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  langs:
  - csharp
  - vb
  name: Include
  nameWithType: AttributionReportingSourceRegistrationTimeConfig.Include
  fullName: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Include
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Include
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
    startLine: 16
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V125.Storage
  summary: Enumerated member for the include value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "include")]

      Include = 0
    return:
      type: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
    content.vb: >-
      <EnumMember(Value:="include")>

      Include = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: include
- uid: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Exclude
  commentId: F:OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Exclude
  id: Exclude
  parent: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  langs:
  - csharp
  - vb
  name: Exclude
  nameWithType: AttributionReportingSourceRegistrationTimeConfig.Exclude
  fullName: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.Exclude
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Exclude
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v125/Storage/AttributionReportingSourceRegistrationTimeConfig.cs
    startLine: 21
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V125.Storage
  summary: Enumerated member for the exclude value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "exclude")]

      Exclude = 1
    return:
      type: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
    content.vb: >-
      <EnumMember(Value:="exclude")>

      Exclude = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: exclude
references:
- uid: OpenQA.Selenium.DevTools.V125.Storage
  commentId: N:OpenQA.Selenium.DevTools.V125.Storage
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V125.Storage
  nameWithType: OpenQA.Selenium.DevTools.V125.Storage
  fullName: OpenQA.Selenium.DevTools.V125.Storage
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V125
    name: V125
    href: OpenQA.Selenium.DevTools.V125.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V125.Storage
    name: Storage
    href: OpenQA.Selenium.DevTools.V125.Storage.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V125
    name: V125
    href: OpenQA.Selenium.DevTools.V125.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V125.Storage
    name: Storage
    href: OpenQA.Selenium.DevTools.V125.Storage.html
- uid: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  commentId: T:OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
  parent: OpenQA.Selenium.DevTools.V125.Storage
  href: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig.html
  name: AttributionReportingSourceRegistrationTimeConfig
  nameWithType: AttributionReportingSourceRegistrationTimeConfig
  fullName: OpenQA.Selenium.DevTools.V125.Storage.AttributionReportingSourceRegistrationTimeConfig
