### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  commentId: T:OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  id: LineStylePatternValues
  parent: OpenQA.Selenium.DevTools.V126.Overlay
  children:
  - OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dashed
  - OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dotted
  langs:
  - csharp
  - vb
  name: LineStylePatternValues
  nameWithType: LineStylePatternValues
  fullName: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: LineStylePatternValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
    startLine: 10
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V126.Overlay
  summary: Enumerated values for Overlay.LineStyle.pattern
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum LineStylePatternValues
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum LineStylePatternValues
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
- uid: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dashed
  commentId: F:OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dashed
  id: Dashed
  parent: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  langs:
  - csharp
  - vb
  name: Dashed
  nameWithType: LineStylePatternValues.Dashed
  fullName: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dashed
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Dashed
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
    startLine: 16
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V126.Overlay
  summary: Enumerated member for the dashed value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "dashed")]

      Dashed = 0
    return:
      type: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
    content.vb: >-
      <EnumMember(Value:="dashed")>

      Dashed = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: dashed
- uid: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dotted
  commentId: F:OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dotted
  id: Dotted
  parent: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  langs:
  - csharp
  - vb
  name: Dotted
  nameWithType: LineStylePatternValues.Dotted
  fullName: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.Dotted
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
      branch: temp_trunk
      repo: https://github.com/titusfortner/selenium
    id: Dotted
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v126/Overlay/LineStylePatternValues.cs
    startLine: 21
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V126.Overlay
  summary: Enumerated member for the dotted value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "dotted")]

      Dotted = 1
    return:
      type: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
    content.vb: >-
      <EnumMember(Value:="dotted")>

      Dotted = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: dotted
references:
- uid: OpenQA.Selenium.DevTools.V126.Overlay
  commentId: N:OpenQA.Selenium.DevTools.V126.Overlay
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V126.Overlay
  nameWithType: OpenQA.Selenium.DevTools.V126.Overlay
  fullName: OpenQA.Selenium.DevTools.V126.Overlay
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V126
    name: V126
    href: OpenQA.Selenium.DevTools.V126.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V126.Overlay
    name: Overlay
    href: OpenQA.Selenium.DevTools.V126.Overlay.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V126
    name: V126
    href: OpenQA.Selenium.DevTools.V126.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V126.Overlay
    name: Overlay
    href: OpenQA.Selenium.DevTools.V126.Overlay.html
- uid: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  commentId: T:OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
  parent: OpenQA.Selenium.DevTools.V126.Overlay
  href: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues.html
  name: LineStylePatternValues
  nameWithType: LineStylePatternValues
  fullName: OpenQA.Selenium.DevTools.V126.Overlay.LineStylePatternValues
