C-java:
  any:
    - '### Does this apply to specific language bindings?\n\n\n\nJava'
    - '### Selenium Language Binding\n\n\n\nJava'

C-py:
  any:
    - '### Does this apply to specific language bindings?\n\n\n\nPython'
    - '### Selenium Language Binding\n\n\n\nPython'

C-dotnet:
  any:
    - '### Does this apply to specific language bindings?\n\n\n\nC#'
    - '### Selenium Language Binding\n\n\n\nC#'

C-rb:
  any:
    - '### Does this apply to specific language bindings?\n\n\n\nRuby'
    - '### Selenium Language Binding\n\n\n\nRuby'

C-nodejs:
  any:
    - '### Does this apply to specific language bindings?\n\n\n\nJavaScript'
    - '### Selenium Language Binding\n\n\n\nJavaScript'

# Component labels
B-atoms:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nAtoms'

B-build:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nBuild'

B-devtools:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nDevTools'

B-docs:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nDocumentation'

B-grid:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nGrid'
    - '### Are you using Selenium Grid?\n\n\n\nYes'

B-manager:
  any:
    - '### What part(s) of Selenium does this relate to?\n\n\n\nSelenium Manager'

# Browser labels
D-chrome:
  any:
    - '### Which browsers are you experiencing the issue with?\n\n\n\nChrome'

D-firefox:
  any:
    - '### Which browsers are you experiencing the issue with?\n\n\n\nFirefox'

D-edge:
  any:
    - '### Which browsers are you experiencing the issue with?\n\n\n\nEdge'

D-safari:
  any:
    - '### Which browsers are you experiencing the issue with?\n\n\n\nSafari'

D-IE:
  any:
    - '### Which browsers are you experiencing the issue with?\n\n\n\nIE'

# OS labels
OS-windows:
  any:
    - '### Operating System\n\n\n\nWindows'

OS-mac:
  any:
    - '### Operating System\n\n\n\nmacOS'

OS-linux:
  any:
    - '### Operating System\n\n\n\nLinux'


I-regression:
  any:
    - '### Did this work for you before?\n\n\n\nYes, this is a regression'
