policy:
  - section:
      - id: bindings
        label:
          - name: C-java
            keys: [ "Java" ]
          - name: C-py
            keys: [ "Python" ]
          - name: C-dotnet
            keys: [ "C#/.NET" ]
          - name: C-rb
            keys: [ "Ruby" ]
          - name: C-nodejs
            keys: [ "JavaScript/Node.js" ]
      - id: regression
        label:
          - name: I-regression
            keys: [ "Yes, this is a regression" ]
