C-java:
  - patterns:
      - java/**

C-py:
  - patterns:
      - py/**

C-dotnet:
  - patterns:
      - dotnet/**

C-rb:
  - patterns:
      - rb/**

C-nodejs:
  - patterns:
      - javascript/selenium-webdriver/**

C-cpp:
  - patterns:
      - cpp/**

C-rust:
  - patterns:
      - rust/**

B-atoms:
  - patterns:
      - javascript/atoms/**

B-grid:
  - patterns:
      - java/src/org/openqa/selenium/grid/**
      - javascript/grid-ui/**

B-manager:
  - patterns:
      - rust/**

B-devtools:
  - patterns:
      - common/devtools/**
      - "**/devtools/**"
      - "**/bidi/**"

B-build:
  - patterns:
      - .github/**
      - scripts/**
      - rake_tasks/**
      - Rakefile
      - BUILD.bazel
      - "**/*.bazel"
      - "**/*.bzl"
      - .bazel*

B-support:
  - patterns:
      - "**/support/**"
