language: java
sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:

  -  export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
  -  export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`

  -  curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
  -  unzip chrome-linux.zip

  -  curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -  unzip chromedriver_linux64.zip

  -  mv chromedriver chrome-linux/chromedriver
  -  chmod +x chrome-linux/chromedriver
  -  export PATH=$PATH:$PWD/chrome-linux

  -  export CHROME_BINARY=$PWD/chrome-linux/chrome
  -  export CHROMEDRIVER=$PWD/chrome-linux/chromedriver

    export PY_FILES_CHANGED=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ^py/`
    if [[ $PY_FILES_CHANGED == py/* ]]; then
      pip install --user virtualenv
      export PATH=$PATH:$HOME/.local/bin
      ./go py_prep_for_install_release //py:phantomjs_test:run
    else
      echo 'no Python files changed - skipping Python test suite'
    fi
  - |
    export RB_FILES_CHANGED=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ^rb/`
    if [[ $RB_FILES_CHANGED == rb/* ]]; then
      export PHANTOMJS_NAME=phantomjs-2.1.1-linux-x86_64
      curl -L -O "https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOMJS_NAME}.tar.bz2"
      tar -xvjf $PHANTOMJS_NAME.tar.bz2
      chmod +x $PHANTOMJS_NAME/bin/phantomjs
      cp $PHANTOMJS_NAME/bin/phantomjs chrome-linux/phantomjs
      export PHANTOMJS_BINARY=$PWD/chrome-linux/phantomjs

      rvm install 2.2.3
      rvm use 2.2.3
      ./go //rb:unit-test //rb:firefox-test //rb:chrome-test //rb:phantomjs-test
    else
      echo 'no Ruby files changed - skipping Ruby test suite'
    fi
