language: ruby
rvm:
- 2.3
before_install:
- export | grep SAUCE_
env:
  global:
  - SAUCE_USERNAME=titusfortner
addons:
  sauce_connect: true
  jwt:
    secure: CRgxAqWgpN3wXLDuu0/5RCZw97js426LbBGGPccfAntT6nr6bVHMczvAAl7M5DFb6fBsO1OdkFn3Oc0T4P+bAaHcC1SMVkvejE59HJAUHcCkkxQ1Z/ly1mJJsg+77AdcsF4l6gyoBWBIGCO0+rdWGyBaTtbQF7RUtiHE8WRGuqY=
