language: java
sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:

  -  export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
  - echo $CHROME_REVISION
  -  export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - echo $CHROMEDRIVER_VERSION

  -  curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
  -  unzip chrome-linux.zip

  -  curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -  unzip chromedriver_linux64.zip

  -  mv chromedriver chrome-linux/chromedriver
  -  chmod +x chrome-linux/chromedriver
  -  export PATH=$PATH:$PWD/chrome-linux

  -  export CHROME_BINARY=$PWD/chrome-linux/chrome
  -  export CHROMEDRIVER=$PWD/chrome-linux/chromedriver

  - |
    export RB_FILES_CHANGED=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ^rb/`
    if [[ $RB_FILES_CHANGED == rb/* ]]; then
      rvm install 2.2.3
      rvm use 2.2.3
      ./go //rb:unit-test //rb:firefox-test //rb:chrome-test
    else
      echo 'no Ruby files changed - skipping Ruby test suite'
    fi
