language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3

  - |

    export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`

    curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/354250/chrome-linux.zip"
    unzip chrome-linux.zip

    curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    unzip chromedriver_linux64.zip

    mv chromedriver chrome-linux/chromedriver
    chmod +x chrome-linux/chromedriver

    export CHROMEDRIVER=$PWD/chrome-linux/chromedriver

  - ./go //rb:chrome-test
