language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3

  - |

    ls -al
    ls -al chrome-linux

    export CHROMEDRIVER=$PWD/chrome-linux/chromedriver

  - ./go //rb:chrome-test
