# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: bluetooth

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Bluetooth
          EVENTS = {
            request_device_prompt_updated: 'bluetooth.requestDevicePromptUpdated',
            gatt_connection_attempted: 'bluetooth.gattConnectionAttempted',
          }.freeze

          SIMULATE_ADAPTER_PARAMETERS_STATE = {
            absent: 'absent',
            powered_off: 'powered-off',
            powered_on: 'powered-on',
          }.freeze

          SIMULATE_SERVICE_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications',
          }.freeze

          SIMULATE_DESCRIPTOR_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
          }.freeze

          CHARACTERISTIC_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write_with_response: 'write-with-response',
            write_without_response: 'write-without-response',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications',
          }.freeze

          DESCRIPTOR_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

          def handle_request_device_prompt(context:, prompt:, accept:, device: nil)
            @bidi.send_cmd('bluetooth.handleRequestDevicePrompt', context: context, prompt: prompt, accept: accept, device: device)
          end

          def simulate_adapter(context:, state:, le_supported: nil)
            @bidi.send_cmd('bluetooth.simulateAdapter', context: context, leSupported: le_supported, state: state)
          end

          def disable_simulation(context:)
            @bidi.send_cmd('bluetooth.disableSimulation', context: context)
          end

          def simulate_preconnected_peripheral(context:, address:, name:, manufacturer_data:, known_service_uuids:)
            @bidi.send_cmd('bluetooth.simulatePreconnectedPeripheral', context: context, address: address, name: name, manufacturerData: manufacturer_data, knownServiceUuids: known_service_uuids)
          end

          def simulate_advertisement(context:, scan_entry:)
            @bidi.send_cmd('bluetooth.simulateAdvertisement', context: context, scanEntry: scan_entry)
          end

          def simulate_gatt_connection_response(context:, address:, code:)
            @bidi.send_cmd('bluetooth.simulateGattConnectionResponse', context: context, address: address, code: code)
          end

          def simulate_gatt_disconnection(context:, address:)
            @bidi.send_cmd('bluetooth.simulateGattDisconnection', context: context, address: address)
          end

          def simulate_service(context:, address:, uuid:, type:)
            @bidi.send_cmd('bluetooth.simulateService', context: context, address: address, uuid: uuid, type: type)
          end

          def simulate_characteristic(context:, address:, service_uuid:, characteristic_uuid:, type:, characteristic_properties: nil)
            @bidi.send_cmd('bluetooth.simulateCharacteristic', context: context, address: address, serviceUuid: service_uuid, characteristicUuid: characteristic_uuid, characteristicProperties: characteristic_properties, type: type)
          end

          def simulate_characteristic_response(context:, address:, service_uuid:, characteristic_uuid:, type:, code:, data: nil)
            @bidi.send_cmd('bluetooth.simulateCharacteristicResponse', context: context, address: address, serviceUuid: service_uuid, characteristicUuid: characteristic_uuid, type: type, code: code, data: data)
          end

          def simulate_descriptor(context:, address:, service_uuid:, characteristic_uuid:, descriptor_uuid:, type:)
            @bidi.send_cmd('bluetooth.simulateDescriptor', context: context, address: address, serviceUuid: service_uuid, characteristicUuid: characteristic_uuid, descriptorUuid: descriptor_uuid, type: type)
          end

          def simulate_descriptor_response(context:, address:, service_uuid:, characteristic_uuid:, descriptor_uuid:, type:, code:, data: nil)
            @bidi.send_cmd('bluetooth.simulateDescriptorResponse', context: context, address: address, serviceUuid: service_uuid, characteristicUuid: characteristic_uuid, descriptorUuid: descriptor_uuid, type: type, code: code, data: data)
          end

        end # Bluetooth
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
