# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: bluetooth

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Bluetooth
          EVENTS = {
            request_device_prompt_updated: 'bluetooth.requestDevicePromptUpdated',
            gatt_connection_attempted: 'bluetooth.gattConnectionAttempted',
          }.freeze

          SIMULATE_ADAPTER_PARAMETERS_STATE = {
            absent: 'absent',
            powered_off: 'powered-off',
            powered_on: 'powered-on',
          }.freeze

          SIMULATE_SERVICE_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications',
          }.freeze

          SIMULATE_DESCRIPTOR_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove',
          }.freeze

          SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
          }.freeze

          CHARACTERISTIC_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write_with_response: 'write-with-response',
            write_without_response: 'write-without-response',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications',
          }.freeze

          DESCRIPTOR_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
          }.freeze

          class BluetoothManufacturerData < Data.define(key: 'key', data: 'data'); end

          class CharacteristicProperties < Data.define(broadcast: 'broadcast', read: 'read', write_without_response: 'writeWithoutResponse', write: 'write', notify: 'notify', indicate: 'indicate', authenticated_signed_writes: 'authenticatedSignedWrites', extended_properties: 'extendedProperties'); end

          class RequestDeviceInfo < Data.define(id: 'id', name: {json_key: 'name', nullable: true}); end

          class ScanRecord < Data.define(name: 'name', uuids: {json_key: 'uuids', list: true}, appearance: 'appearance', manufacturer_data: {json_key: 'manufacturerData', ref: 'Bluetooth::BluetoothManufacturerData', list: true}); end

          class HandleRequestDevicePrompt < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.handleRequestDevicePrompt'}, params: {json_key: 'params', ref: 'Bluetooth::HandleRequestDevicePromptParameters'}); end

          class HandleRequestDevicePromptParameters < Union
            discriminator 'accept'
            variants(
              true => 'Bluetooth::HandleRequestDevicePromptParameters::AcceptParameters',
              false => 'Bluetooth::HandleRequestDevicePromptParameters::CancelParameters',
            )

            class AcceptParameters < Data.define(accept: {fixed: true}, context: 'context', prompt: 'prompt', device: 'device'); end

            class CancelParameters < Data.define(accept: {fixed: false}, context: 'context', prompt: 'prompt'); end
          end

          class SimulateAdapter < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateAdapter'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateAdapterParameters'}); end

          class SimulateAdapterParameters < Data.define(context: 'context', le_supported: 'leSupported', state: 'state'); end

          class DisableSimulation < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.disableSimulation'}, params: {json_key: 'params', ref: 'Bluetooth::DisableSimulationParameters'}); end

          class DisableSimulationParameters < Data.define(context: 'context'); end

          class SimulatePreconnectedPeripheral < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulatePreconnectedPeripheral'}, params: {json_key: 'params', ref: 'Bluetooth::SimulatePreconnectedPeripheralParameters'}); end

          class SimulatePreconnectedPeripheralParameters < Data.define(context: 'context', address: 'address', name: 'name', manufacturer_data: {json_key: 'manufacturerData', ref: 'Bluetooth::BluetoothManufacturerData', list: true}, known_service_uuids: {json_key: 'knownServiceUuids', list: true}); end

          class SimulateAdvertisement < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateAdvertisement'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateAdvertisementParameters'}); end

          class SimulateAdvertisementParameters < Data.define(context: 'context', scan_entry: {json_key: 'scanEntry', ref: 'Bluetooth::SimulateAdvertisementScanEntryParameters'}); end

          class SimulateAdvertisementScanEntryParameters < Data.define(device_address: 'deviceAddress', rssi: 'rssi', scan_record: {json_key: 'scanRecord', ref: 'Bluetooth::ScanRecord'}); end

          class SimulateGattConnectionResponse < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateGattConnectionResponse'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateGattConnectionResponseParameters'}); end

          class SimulateGattConnectionResponseParameters < Data.define(context: 'context', address: 'address', code: 'code'); end

          class SimulateGattDisconnection < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateGattDisconnection'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateGattDisconnectionParameters'}); end

          class SimulateGattDisconnectionParameters < Data.define(context: 'context', address: 'address'); end

          class SimulateService < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateService'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateServiceParameters'}); end

          class SimulateServiceParameters < Data.define(context: 'context', address: 'address', uuid: 'uuid', type: 'type'); end

          class SimulateCharacteristic < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateCharacteristic'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateCharacteristicParameters'}); end

          class SimulateCharacteristicParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', characteristic_properties: {json_key: 'characteristicProperties', ref: 'Bluetooth::CharacteristicProperties'}, type: 'type'); end

          class SimulateCharacteristicResponse < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateCharacteristicResponse'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateCharacteristicResponseParameters'}); end

          class SimulateCharacteristicResponseParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', type: 'type', code: 'code', data: {json_key: 'data', list: true}); end

          class SimulateDescriptor < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateDescriptor'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateDescriptorParameters'}); end

          class SimulateDescriptorParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', descriptor_uuid: 'descriptorUuid', type: 'type'); end

          class SimulateDescriptorResponse < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.simulateDescriptorResponse'}, params: {json_key: 'params', ref: 'Bluetooth::SimulateDescriptorResponseParameters'}); end

          class SimulateDescriptorResponseParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', descriptor_uuid: 'descriptorUuid', type: 'type', code: 'code', data: {json_key: 'data', list: true}); end

          class RequestDevicePromptUpdated < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.requestDevicePromptUpdated'}, params: {json_key: 'params', ref: 'Bluetooth::RequestDevicePromptUpdatedParameters'}); end

          class RequestDevicePromptUpdatedParameters < Data.define(context: 'context', prompt: 'prompt', devices: {json_key: 'devices', ref: 'Bluetooth::RequestDeviceInfo', list: true}); end

          class GattConnectionAttempted < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.gattConnectionAttempted'}, params: {json_key: 'params', ref: 'Bluetooth::GattConnectionAttemptedParameters'}); end

          class GattConnectionAttemptedParameters < Data.define(context: 'context', address: 'address'); end

          class CharacteristicEventGenerated < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.characteristicEventGenerated'}, params: {json_key: 'params', ref: 'Bluetooth::CharacteristicEventGeneratedParameters'}); end

          class CharacteristicEventGeneratedParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', type: 'type', data: {json_key: 'data', list: true}); end

          class DescriptorEventGenerated < Data.define(method_: {json_key: 'method', fixed: 'bluetooth.descriptorEventGenerated'}, params: {json_key: 'params', ref: 'Bluetooth::DescriptorEventGeneratedParameters'}); end

          class DescriptorEventGeneratedParameters < Data.define(context: 'context', address: 'address', service_uuid: 'serviceUuid', characteristic_uuid: 'characteristicUuid', descriptor_uuid: 'descriptorUuid', type: 'type', data: {json_key: 'data', list: true}); end

          def initialize(context)
            @transport = Transport.for(context)
          end

          def handle_request_device_prompt(context:, prompt:, accept:, device: UNSET)
            @transport.execute('bluetooth.handleRequestDevicePrompt', HandleRequestDevicePromptParameters.build(context: context, prompt: prompt, accept: accept, device: device))
          end

          def simulate_adapter(context:, state:, le_supported: UNSET)
            Enum.check!('state', state, Bluetooth::SIMULATE_ADAPTER_PARAMETERS_STATE)
            @transport.execute('bluetooth.simulateAdapter', SimulateAdapterParameters.new(context: context, le_supported: le_supported, state: state))
          end

          def disable_simulation(context:)
            @transport.execute('bluetooth.disableSimulation', DisableSimulationParameters.new(context: context))
          end

          def simulate_preconnected_peripheral(context:, address:, name:, manufacturer_data:, known_service_uuids:)
            @transport.execute('bluetooth.simulatePreconnectedPeripheral', SimulatePreconnectedPeripheralParameters.new(context: context, address: address, name: name, manufacturer_data: manufacturer_data, known_service_uuids: known_service_uuids))
          end

          def simulate_advertisement(context:, scan_entry:)
            @transport.execute('bluetooth.simulateAdvertisement', SimulateAdvertisementParameters.new(context: context, scan_entry: scan_entry))
          end

          def simulate_gatt_connection_response(context:, address:, code:)
            @transport.execute('bluetooth.simulateGattConnectionResponse', SimulateGattConnectionResponseParameters.new(context: context, address: address, code: code))
          end

          def simulate_gatt_disconnection(context:, address:)
            @transport.execute('bluetooth.simulateGattDisconnection', SimulateGattDisconnectionParameters.new(context: context, address: address))
          end

          def simulate_service(context:, address:, uuid:, type:)
            Enum.check!('type', type, Bluetooth::SIMULATE_SERVICE_PARAMETERS_TYPE)
            @transport.execute('bluetooth.simulateService', SimulateServiceParameters.new(context: context, address: address, uuid: uuid, type: type))
          end

          def simulate_characteristic(context:, address:, service_uuid:, characteristic_uuid:, type:, characteristic_properties: UNSET)
            Enum.check!('type', type, Bluetooth::SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE)
            @transport.execute('bluetooth.simulateCharacteristic', SimulateCharacteristicParameters.new(context: context, address: address, service_uuid: service_uuid, characteristic_uuid: characteristic_uuid, characteristic_properties: characteristic_properties, type: type))
          end

          def simulate_characteristic_response(context:, address:, service_uuid:, characteristic_uuid:, type:, code:, data: UNSET)
            Enum.check!('type', type, Bluetooth::SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE)
            @transport.execute('bluetooth.simulateCharacteristicResponse', SimulateCharacteristicResponseParameters.new(context: context, address: address, service_uuid: service_uuid, characteristic_uuid: characteristic_uuid, type: type, code: code, data: data))
          end

          def simulate_descriptor(context:, address:, service_uuid:, characteristic_uuid:, descriptor_uuid:, type:)
            Enum.check!('type', type, Bluetooth::SIMULATE_DESCRIPTOR_PARAMETERS_TYPE)
            @transport.execute('bluetooth.simulateDescriptor', SimulateDescriptorParameters.new(context: context, address: address, service_uuid: service_uuid, characteristic_uuid: characteristic_uuid, descriptor_uuid: descriptor_uuid, type: type))
          end

          def simulate_descriptor_response(context:, address:, service_uuid:, characteristic_uuid:, descriptor_uuid:, type:, code:, data: UNSET)
            Enum.check!('type', type, Bluetooth::SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE)
            @transport.execute('bluetooth.simulateDescriptorResponse', SimulateDescriptorResponseParameters.new(context: context, address: address, service_uuid: service_uuid, characteristic_uuid: characteristic_uuid, descriptor_uuid: descriptor_uuid, type: type, code: code, data: data))
          end

        end # Bluetooth
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
