# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: browser

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Browser
          CLIENT_WINDOW_INFO_STATE = {
            fullscreen: 'fullscreen',
            maximized: 'maximized',
            minimized: 'minimized',
            normal: 'normal',
          }.freeze

          CLIENT_WINDOW_NAMED_STATE_STATE = {
            fullscreen: 'fullscreen',
            maximized: 'maximized',
            minimized: 'minimized',
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ClientWindowInfo < Data.define(active: 'active', client_window: 'clientWindow', height: 'height', state: {json_key: 'state', enum: 'Browser::CLIENT_WINDOW_INFO_STATE'}, width: 'width', x: 'x', y: 'y'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class UserContextInfo < Data.define(user_context: 'userContext'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class CreateUserContextParameters < Data.define(accept_insecure_certs: 'acceptInsecureCerts', proxy: {json_key: 'proxy', ref: 'Session::ProxyConfiguration'}, unhandled_prompt_behavior: {json_key: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class GetClientWindowsResult < Data.define(client_windows: {json_key: 'clientWindows', ref: 'Browser::ClientWindowInfo', list: true}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class GetUserContextsResult < Data.define(user_contexts: {json_key: 'userContexts', ref: 'Browser::UserContextInfo', list: true}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class RemoveUserContextParameters < Data.define(user_context: 'userContext'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class SetClientWindowStateParameters < Union
            discriminator 'state'
            variants(
              'normal' => 'Browser::SetClientWindowStateParameters::ClientWindowRectState',
            )
            fallback 'Browser::SetClientWindowStateParameters::ClientWindowNamedState'

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            class ClientWindowNamedState < Data.define(client_window: 'clientWindow', state: {json_key: 'state', enum: 'Browser::CLIENT_WINDOW_NAMED_STATE_STATE'}); end

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            class ClientWindowRectState < Data.define(state: {fixed: 'normal'}, client_window: 'clientWindow', width: 'width', height: 'height', x: 'x', y: 'y'); end
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class SetDownloadBehaviorParameters < Data.define(download_behavior: {json_key: 'downloadBehavior', nullable: true, ref: 'Browser::DownloadBehavior'}, user_contexts: {json_key: 'userContexts', list: true}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class DownloadBehavior < Union
            discriminator 'type'
            variants(
              'allowed' => 'Browser::DownloadBehavior::Allowed',
              'denied' => 'Browser::DownloadBehavior::Denied',
            )

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            class Allowed < Data.define(type: {fixed: 'allowed'}, destination_folder: 'destinationFolder'); end

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            class Denied < Data.define(type: {fixed: 'denied'}); end
          end

          def initialize(context)
            @transport = Transport.for(context)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def close
            @transport.execute(cmd: 'browser.close')
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def create_user_context(accept_insecure_certs: UNSET, proxy: UNSET, unhandled_prompt_behavior: UNSET)
            @transport.execute(cmd: 'browser.createUserContext', params: CreateUserContextParameters.new(accept_insecure_certs: accept_insecure_certs, proxy: proxy, unhandled_prompt_behavior: unhandled_prompt_behavior), result: Browser::UserContextInfo)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def get_client_windows
            @transport.execute(cmd: 'browser.getClientWindows', result: Browser::GetClientWindowsResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def get_user_contexts
            @transport.execute(cmd: 'browser.getUserContexts', result: Browser::GetUserContextsResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def remove_user_context(user_context:)
            @transport.execute(cmd: 'browser.removeUserContext', params: RemoveUserContextParameters.new(user_context: user_context))
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_client_window_state(client_window:, state:, width: UNSET, height: UNSET, x: UNSET, y: UNSET)
            Enum.check!('state', state, %w[normal fullscreen maximized minimized])
            @transport.execute(cmd: 'browser.setClientWindowState', params: SetClientWindowStateParameters.build(client_window: client_window, state: state, width: width, height: height, x: x, y: y), result: Browser::ClientWindowInfo)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_download_behavior(download_behavior:, user_contexts: UNSET)
            @transport.execute(cmd: 'browser.setDownloadBehavior', params: SetDownloadBehaviorParameters.new(download_behavior: download_behavior, user_contexts: user_contexts))
          end

        end # Browser
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
