# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: browser

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Browser
          CLIENT_WINDOW_INFO_STATE = {
            fullscreen: 'fullscreen',
            maximized: 'maximized',
            minimized: 'minimized',
            normal: 'normal',
          }.freeze

          CLIENT_WINDOW_NAMED_STATE_STATE = {
            fullscreen: 'fullscreen',
            maximized: 'maximized',
            minimized: 'minimized',
          }.freeze

          class ClientWindowInfo < Data.define(active: 'active', client_window: 'clientWindow', height: 'height', state: 'state', width: 'width', x: 'x', y: 'y'); end

          class UserContextInfo < Data.define(user_context: 'userContext'); end

          class Close < Data.define(method_: {json_key: 'method', fixed: 'browser.close'}, params: 'params'); end

          class CreateUserContext < Data.define(method_: {json_key: 'method', fixed: 'browser.createUserContext'}, params: {json_key: 'params', ref: 'Browser::CreateUserContextParameters'}); end

          class CreateUserContextParameters < Data.define(accept_insecure_certs: 'acceptInsecureCerts', proxy: {json_key: 'proxy', ref: 'Session::ProxyConfiguration'}, unhandled_prompt_behavior: {json_key: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'}); end

          class GetClientWindows < Data.define(method_: {json_key: 'method', fixed: 'browser.getClientWindows'}, params: 'params'); end

          class GetClientWindowsResult < Data.define(client_windows: {json_key: 'clientWindows', ref: 'Browser::ClientWindowInfo', list: true}); end

          class GetUserContexts < Data.define(method_: {json_key: 'method', fixed: 'browser.getUserContexts'}, params: 'params'); end

          class GetUserContextsResult < Data.define(user_contexts: {json_key: 'userContexts', ref: 'Browser::UserContextInfo', list: true}); end

          class RemoveUserContext < Data.define(method_: {json_key: 'method', fixed: 'browser.removeUserContext'}, params: {json_key: 'params', ref: 'Browser::RemoveUserContextParameters'}); end

          class RemoveUserContextParameters < Data.define(user_context: 'userContext'); end

          class SetClientWindowState < Data.define(method_: {json_key: 'method', fixed: 'browser.setClientWindowState'}, params: {json_key: 'params', ref: 'Browser::SetClientWindowStateParameters'}); end

          class SetClientWindowStateParameters < Union
            discriminator 'state'
            variants(
              'normal' => 'Browser::SetClientWindowStateParameters::ClientWindowRectState',
            )
            fallback 'Browser::SetClientWindowStateParameters::ClientWindowNamedState'

            class ClientWindowNamedState < Data.define(client_window: 'clientWindow', state: 'state'); end

            class ClientWindowRectState < Data.define(state: {fixed: 'normal'}, client_window: 'clientWindow', width: 'width', height: 'height', x: 'x', y: 'y'); end
          end

          class SetDownloadBehavior < Data.define(method_: {json_key: 'method', fixed: 'browser.setDownloadBehavior'}, params: {json_key: 'params', ref: 'Browser::SetDownloadBehaviorParameters'}); end

          class SetDownloadBehaviorParameters < Data.define(download_behavior: {json_key: 'downloadBehavior', nullable: true, ref: 'Browser::DownloadBehavior'}, user_contexts: {json_key: 'userContexts', list: true}); end

          class DownloadBehavior < Union
            discriminator 'type'
            variants(
              'allowed' => 'Browser::DownloadBehavior::Allowed',
              'denied' => 'Browser::DownloadBehavior::Denied',
            )

            class Allowed < Data.define(type: {fixed: 'allowed'}, destination_folder: 'destinationFolder'); end

            class Denied < Data.define(type: {fixed: 'denied'}); end
          end

          def initialize(bidi)
            @bidi = bidi
          end

          def close
            @bidi.send_cmd('browser.close')
          end

          def create_user_context(accept_insecure_certs: nil, proxy: nil, unhandled_prompt_behavior: nil)
            result = @bidi.send_cmd('browser.createUserContext', acceptInsecureCerts: accept_insecure_certs, proxy: proxy, unhandledPromptBehavior: unhandled_prompt_behavior)
            Protocol.const_get('Browser::UserContextInfo').from_json(result)
          end

          def get_client_windows
            result = @bidi.send_cmd('browser.getClientWindows')
            Protocol.const_get('Browser::GetClientWindowsResult').from_json(result)
          end

          def get_user_contexts
            result = @bidi.send_cmd('browser.getUserContexts')
            Protocol.const_get('Browser::GetUserContextsResult').from_json(result)
          end

          def remove_user_context(user_context:)
            @bidi.send_cmd('browser.removeUserContext', userContext: user_context)
          end

          def set_client_window_state(client_window:, state:, width: nil, height: nil, x: nil, y: nil)
            result = @bidi.send_cmd('browser.setClientWindowState', clientWindow: client_window, state: state, width: width, height: height, x: x, y: y)
            Protocol.const_get('Browser::ClientWindowInfo').from_json(result)
          end

          def set_download_behavior(download_behavior:, user_contexts: nil)
            @bidi.send_cmd('browser.setDownloadBehavior', downloadBehavior: download_behavior, userContexts: user_contexts)
          end

        end # Browser
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
