# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: browsingContext

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class BrowsingContext
          EVENTS = {
            context_created: 'browsingContext.contextCreated',
            context_destroyed: 'browsingContext.contextDestroyed',
            dom_content_loaded: 'browsingContext.domContentLoaded',
            download_end: 'browsingContext.downloadEnd',
            download_will_begin: 'browsingContext.downloadWillBegin',
            fragment_navigated: 'browsingContext.fragmentNavigated',
            history_updated: 'browsingContext.historyUpdated',
            load: 'browsingContext.load',
            navigation_aborted: 'browsingContext.navigationAborted',
            navigation_committed: 'browsingContext.navigationCommitted',
            navigation_failed: 'browsingContext.navigationFailed',
            navigation_started: 'browsingContext.navigationStarted',
            user_prompt_closed: 'browsingContext.userPromptClosed',
            user_prompt_opened: 'browsingContext.userPromptOpened',
          }.freeze

          READINESS_STATE = {
            none: 'none',
            interactive: 'interactive',
            complete: 'complete',
          }.freeze

          USER_PROMPT_TYPE = {
            alert: 'alert',
            beforeunload: 'beforeunload',
            confirm: 'confirm',
            prompt: 'prompt',
          }.freeze

          CREATE_TYPE = {
            tab: 'tab',
            window: 'window',
          }.freeze

          INNER_TEXT_LOCATOR_MATCH_TYPE = {
            full: 'full',
            partial: 'partial',
          }.freeze

          CAPTURE_SCREENSHOT_PARAMETERS_ORIGIN = {
            viewport: 'viewport',
            document: 'document',
          }.freeze

          PRINT_PARAMETERS_ORIENTATION = {
            portrait: 'portrait',
            landscape: 'landscape',
          }.freeze

          class Info < Data.define(children: {json_key: 'children', nullable: true, ref: 'BrowsingContext::Info', list: true}, client_window: 'clientWindow', context: 'context', original_opener: {json_key: 'originalOpener', nullable: true}, url: 'url', user_context: 'userContext', parent: {json_key: 'parent', nullable: true}); end

          class Locator < Union
            discriminator 'type'
            variants(
              'accessibility' => 'BrowsingContext::AccessibilityLocator',
              'css' => 'BrowsingContext::CssLocator',
              'context' => 'BrowsingContext::ContextLocator',
              'innerText' => 'BrowsingContext::InnerTextLocator',
              'xpath' => 'BrowsingContext::XPathLocator',
            )
          end

          class AccessibilityLocator < Data.define(type: {fixed: 'accessibility'}, value: {json_key: 'value', ref: 'BrowsingContext::AccessibilityLocator::Value'})
            class Value < Data.define(name: 'name', role: 'role'); end
          end

          class CssLocator < Data.define(type: {fixed: 'css'}, value: 'value'); end

          class ContextLocator < Data.define(type: {fixed: 'context'}, value: {json_key: 'value', ref: 'BrowsingContext::ContextLocator::Value'})
            class Value < Data.define(context: 'context'); end
          end

          class InnerTextLocator < Data.define(type: {fixed: 'innerText'}, value: 'value', ignore_case: 'ignoreCase', match_type: 'matchType', max_depth: 'maxDepth'); end

          class XPathLocator < Data.define(type: {fixed: 'xpath'}, value: 'value'); end

          class BaseNavigationInfo < Data.define(context: 'context', navigation: {json_key: 'navigation', nullable: true}, timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end

          class NavigationInfo < Data.define(context: 'context', navigation: {json_key: 'navigation', nullable: true}, timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end

          class Activate < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.activate'}, params: {json_key: 'params', ref: 'BrowsingContext::ActivateParameters'}); end

          class ActivateParameters < Data.define(context: 'context'); end

          class CaptureScreenshot < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.captureScreenshot'}, params: {json_key: 'params', ref: 'BrowsingContext::CaptureScreenshotParameters'}); end

          class CaptureScreenshotParameters < Data.define(context: 'context', origin: 'origin', format: {json_key: 'format', ref: 'BrowsingContext::ImageFormat'}, clip: {json_key: 'clip', ref: 'BrowsingContext::ClipRectangle'}); end

          class ImageFormat < Data.define(type: 'type', quality: 'quality'); end

          class ClipRectangle < Union
            discriminator 'type'
            variants(
              'box' => 'BrowsingContext::BoxClipRectangle',
              'element' => 'BrowsingContext::ElementClipRectangle',
            )
          end

          class ElementClipRectangle < Data.define(type: {fixed: 'element'}, element: {json_key: 'element', ref: 'Script::SharedReference'}); end

          class BoxClipRectangle < Data.define(type: {fixed: 'box'}, x: 'x', y: 'y', width: 'width', height: 'height'); end

          class CaptureScreenshotResult < Data.define(data: 'data'); end

          class Close < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.close'}, params: {json_key: 'params', ref: 'BrowsingContext::CloseParameters'}); end

          class CloseParameters < Data.define(context: 'context', prompt_unload: 'promptUnload'); end

          class Create < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.create'}, params: {json_key: 'params', ref: 'BrowsingContext::CreateParameters'}); end

          class CreateParameters < Data.define(type: 'type', reference_context: 'referenceContext', background: 'background', user_context: 'userContext'); end

          class CreateResult < Data.define(context: 'context', user_context: 'userContext'); end

          class GetTree < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.getTree'}, params: {json_key: 'params', ref: 'BrowsingContext::GetTreeParameters'}); end

          class GetTreeParameters < Data.define(max_depth: 'maxDepth', root: 'root'); end

          class GetTreeResult < Data.define(contexts: {json_key: 'contexts', ref: 'BrowsingContext::Info', list: true}); end

          class HandleUserPrompt < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.handleUserPrompt'}, params: {json_key: 'params', ref: 'BrowsingContext::HandleUserPromptParameters'}); end

          class HandleUserPromptParameters < Data.define(context: 'context', accept: 'accept', user_text: 'userText'); end

          class LocateNodes < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.locateNodes'}, params: {json_key: 'params', ref: 'BrowsingContext::LocateNodesParameters'}); end

          class LocateNodesParameters < Data.define(context: 'context', locator: {json_key: 'locator', ref: 'BrowsingContext::Locator'}, max_node_count: 'maxNodeCount', serialization_options: {json_key: 'serializationOptions', ref: 'Script::SerializationOptions'}, start_nodes: {json_key: 'startNodes', ref: 'Script::SharedReference', list: true}); end

          class LocateNodesResult < Data.define(nodes: {json_key: 'nodes', ref: 'Script::NodeRemoteValue', list: true}); end

          class Navigate < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.navigate'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigateParameters'}); end

          class NavigateParameters < Data.define(context: 'context', url: 'url', wait: 'wait'); end

          class NavigateResult < Data.define(navigation: {json_key: 'navigation', nullable: true}, url: 'url'); end

          class Print < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.print'}, params: {json_key: 'params', ref: 'BrowsingContext::PrintParameters'}); end

          class PrintParameters < Data.define(context: 'context', background: 'background', margin: {json_key: 'margin', ref: 'BrowsingContext::PrintMarginParameters'}, orientation: 'orientation', page: {json_key: 'page', ref: 'BrowsingContext::PrintPageParameters'}, page_ranges: {json_key: 'pageRanges', list: true}, scale: 'scale', shrink_to_fit: 'shrinkToFit'); end

          class PrintMarginParameters < Data.define(bottom: 'bottom', left: 'left', right: 'right', top: 'top'); end

          class PrintPageParameters < Data.define(height: 'height', width: 'width'); end

          class PrintResult < Data.define(data: 'data'); end

          class Reload < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.reload'}, params: {json_key: 'params', ref: 'BrowsingContext::ReloadParameters'}); end

          class ReloadParameters < Data.define(context: 'context', ignore_cache: 'ignoreCache', wait: 'wait'); end

          class SetBypassCSP < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.setBypassCSP'}, params: {json_key: 'params', ref: 'BrowsingContext::SetBypassCSPParameters'}); end

          class SetBypassCSPParameters < Data.define(bypass: {fixed: true}, contexts: {json_key: 'contexts', list: true}, user_contexts: {json_key: 'userContexts', list: true}); end

          class SetViewport < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.setViewport'}, params: {json_key: 'params', ref: 'BrowsingContext::SetViewportParameters'}); end

          class SetViewportParameters < Data.define(context: 'context', viewport: {json_key: 'viewport', nullable: true, ref: 'BrowsingContext::Viewport'}, device_pixel_ratio: {json_key: 'devicePixelRatio', nullable: true}, user_contexts: {json_key: 'userContexts', list: true}); end

          class Viewport < Data.define(width: 'width', height: 'height'); end

          class TraverseHistory < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.traverseHistory'}, params: {json_key: 'params', ref: 'BrowsingContext::TraverseHistoryParameters'}); end

          class TraverseHistoryParameters < Data.define(context: 'context', delta: 'delta'); end

          class ContextCreated < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.contextCreated'}, params: {json_key: 'params', ref: 'BrowsingContext::Info'}); end

          class ContextDestroyed < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.contextDestroyed'}, params: {json_key: 'params', ref: 'BrowsingContext::Info'}); end

          class NavigationStarted < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.navigationStarted'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class FragmentNavigated < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.fragmentNavigated'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class HistoryUpdated < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.historyUpdated'}, params: {json_key: 'params', ref: 'BrowsingContext::HistoryUpdatedParameters'}); end

          class HistoryUpdatedParameters < Data.define(context: 'context', timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end

          class DomContentLoaded < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.domContentLoaded'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class Load < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.load'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class DownloadWillBegin < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.downloadWillBegin'}, params: {json_key: 'params', ref: 'BrowsingContext::DownloadWillBeginParams'}); end

          class DownloadWillBeginParams < Data.define(suggested_filename: 'suggestedFilename', context: 'context', navigation: {json_key: 'navigation', nullable: true}, timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end

          class DownloadEnd < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.downloadEnd'}, params: {json_key: 'params', ref: 'BrowsingContext::DownloadEndParams'}); end

          class DownloadEndParams < Union
            discriminator 'status'
            variants(
              'canceled' => 'BrowsingContext::DownloadEndParams::CanceledParams',
              'complete' => 'BrowsingContext::DownloadEndParams::CompleteParams',
            )

            class CanceledParams < Data.define(status: {fixed: 'canceled'}, context: 'context', navigation: {json_key: 'navigation', nullable: true}, timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end

            class CompleteParams < Data.define(status: {fixed: 'complete'}, filepath: {json_key: 'filepath', nullable: true}, context: 'context', navigation: {json_key: 'navigation', nullable: true}, timestamp: 'timestamp', url: 'url', user_context: 'userContext'); end
          end

          class NavigationAborted < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.navigationAborted'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class NavigationCommitted < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.navigationCommitted'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class NavigationFailed < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.navigationFailed'}, params: {json_key: 'params', ref: 'BrowsingContext::NavigationInfo'}); end

          class UserPromptClosed < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.userPromptClosed'}, params: {json_key: 'params', ref: 'BrowsingContext::UserPromptClosedParameters'}); end

          class UserPromptClosedParameters < Data.define(context: 'context', accepted: 'accepted', type: 'type', user_context: 'userContext', user_text: 'userText'); end

          class UserPromptOpened < Data.define(method_: {json_key: 'method', fixed: 'browsingContext.userPromptOpened'}, params: {json_key: 'params', ref: 'BrowsingContext::UserPromptOpenedParameters'}); end

          class UserPromptOpenedParameters < Data.define(context: 'context', handler: 'handler', message: 'message', type: 'type', user_context: 'userContext', default_value: 'defaultValue'); end

          def initialize(transport)
            @transport = transport
          end

          def activate(context:)
            @transport.execute('browsingContext.activate', {context: context})
          end

          def capture_screenshot(context:, origin: nil, format: nil, clip: nil)
            @transport.execute('browsingContext.captureScreenshot', {context: context, origin: origin, format: format, clip: clip}, returns: Protocol.const_get('BrowsingContext::CaptureScreenshotResult'))
          end

          def close(context:, prompt_unload: nil)
            @transport.execute('browsingContext.close', {context: context, promptUnload: prompt_unload})
          end

          def create(type:, reference_context: nil, background: nil, user_context: nil)
            @transport.execute('browsingContext.create', {type: type, referenceContext: reference_context, background: background, userContext: user_context}, returns: Protocol.const_get('BrowsingContext::CreateResult'))
          end

          def get_tree(max_depth: nil, root: nil)
            @transport.execute('browsingContext.getTree', {maxDepth: max_depth, root: root}, returns: Protocol.const_get('BrowsingContext::GetTreeResult'))
          end

          def handle_user_prompt(context:, accept: nil, user_text: nil)
            @transport.execute('browsingContext.handleUserPrompt', {context: context, accept: accept, userText: user_text})
          end

          def locate_nodes(context:, locator:, max_node_count: nil, serialization_options: nil, start_nodes: nil)
            @transport.execute('browsingContext.locateNodes', {context: context, locator: locator, maxNodeCount: max_node_count, serializationOptions: serialization_options, startNodes: start_nodes}, returns: Protocol.const_get('BrowsingContext::LocateNodesResult'))
          end

          def navigate(context:, url:, wait: nil)
            @transport.execute('browsingContext.navigate', {context: context, url: url, wait: wait}, returns: Protocol.const_get('BrowsingContext::NavigateResult'))
          end

          def print(context:, background: nil, margin: nil, orientation: nil, page: nil, page_ranges: nil, scale: nil, shrink_to_fit: nil)
            @transport.execute('browsingContext.print', {context: context, background: background, margin: margin, orientation: orientation, page: page, pageRanges: page_ranges, scale: scale, shrinkToFit: shrink_to_fit}, returns: Protocol.const_get('BrowsingContext::PrintResult'))
          end

          def reload(context:, ignore_cache: nil, wait: nil)
            @transport.execute('browsingContext.reload', {context: context, ignoreCache: ignore_cache, wait: wait}, returns: Protocol.const_get('BrowsingContext::NavigateResult'))
          end

          def set_bypass_csp(bypass:, contexts: nil, user_contexts: nil)
            @transport.execute('browsingContext.setBypassCSP', {bypass: bypass, contexts: contexts, userContexts: user_contexts})
          end

          def set_viewport(context: nil, viewport: nil, device_pixel_ratio: nil, user_contexts: nil)
            @transport.execute('browsingContext.setViewport', {context: context, viewport: viewport, devicePixelRatio: device_pixel_ratio, userContexts: user_contexts})
          end

          def traverse_history(context:, delta:)
            @transport.execute('browsingContext.traverseHistory', {context: context, delta: delta})
          end

        end # BrowsingContext
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
