# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: emulation

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Emulation
          FORCED_COLORS_MODE_THEME = {
            light: 'light',
            dark: 'dark',
          }.freeze

          SCREEN_ORIENTATION_NATURAL = {
            portrait: 'portrait',
            landscape: 'landscape',
          }.freeze

          SCREEN_ORIENTATION_TYPE = {
            portrait_primary: 'portrait-primary',
            portrait_secondary: 'portrait-secondary',
            landscape_primary: 'landscape-primary',
            landscape_secondary: 'landscape-secondary',
          }.freeze

          class SetForcedColorsModeThemeOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setForcedColorsModeThemeOverride'}, params: {wire: 'params', ref: 'Emulation::SetForcedColorsModeThemeOverrideParameters'}); end

          class SetForcedColorsModeThemeOverrideParameters < Data.define(theme: {wire: 'theme', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetGeolocationOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setGeolocationOverride'}, params: {wire: 'params', ref: 'Emulation::SetGeolocationOverrideParameters'}); end

          class SetGeolocationOverrideParameters < Union
            presence(
              'Emulation::SetGeolocationOverrideParameters_Coordinates' => ['coordinates'],
              'Emulation::SetGeolocationOverrideParameters_Error' => ['error'],
            )
          end

          class GeolocationCoordinates < Data.define(latitude: 'latitude', longitude: 'longitude', accuracy: 'accuracy', altitude: {wire: 'altitude', nullable: true}, altitude_accuracy: {wire: 'altitudeAccuracy', nullable: true}, heading: {wire: 'heading', nullable: true}, speed: {wire: 'speed', nullable: true}); end

          class GeolocationPositionError < Data.define(type: {fixed: 'positionUnavailable'}); end

          class SetLocaleOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setLocaleOverride'}, params: {wire: 'params', ref: 'Emulation::SetLocaleOverrideParameters'}); end

          class SetLocaleOverrideParameters < Data.define(locale: {wire: 'locale', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetNetworkConditions < Data.define(method_: {wire: 'method', fixed: 'emulation.setNetworkConditions'}, params: {wire: 'params', ref: 'Emulation::SetNetworkConditionsParameters'}); end

          class SetNetworkConditionsParameters < Data.define(network_conditions: {wire: 'networkConditions', nullable: true, ref: 'Emulation::NetworkConditionsOffline'}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class NetworkConditionsOffline < Data.define(type: {fixed: 'offline'}); end

          class SetScreenSettingsOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setScreenSettingsOverride'}, params: {wire: 'params', ref: 'Emulation::SetScreenSettingsOverrideParameters'}); end

          class ScreenArea < Data.define(width: 'width', height: 'height'); end

          class SetScreenSettingsOverrideParameters < Data.define(screen_area: {wire: 'screenArea', nullable: true, ref: 'Emulation::ScreenArea'}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetScreenOrientationOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setScreenOrientationOverride'}, params: {wire: 'params', ref: 'Emulation::SetScreenOrientationOverrideParameters'}); end

          class ScreenOrientation < Data.define(natural: 'natural', type: 'type'); end

          class SetScreenOrientationOverrideParameters < Data.define(screen_orientation: {wire: 'screenOrientation', nullable: true, ref: 'Emulation::ScreenOrientation'}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetUserAgentOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setUserAgentOverride'}, params: {wire: 'params', ref: 'Emulation::SetUserAgentOverrideParameters'}); end

          class SetUserAgentOverrideParameters < Data.define(user_agent: {wire: 'userAgent', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetScriptingEnabled < Data.define(method_: {wire: 'method', fixed: 'emulation.setScriptingEnabled'}, params: {wire: 'params', ref: 'Emulation::SetScriptingEnabledParameters'}); end

          class SetScriptingEnabledParameters < Data.define(enabled: {fixed: false}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetScrollbarTypeOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setScrollbarTypeOverride'}, params: {wire: 'params', ref: 'Emulation::SetScrollbarTypeOverrideParameters'}); end

          class SetScrollbarTypeOverrideParameters < Data.define(scrollbar_type: {wire: 'scrollbarType', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetTimezoneOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setTimezoneOverride'}, params: {wire: 'params', ref: 'Emulation::SetTimezoneOverrideParameters'}); end

          class SetTimezoneOverrideParameters < Data.define(timezone: {wire: 'timezone', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetTouchOverride < Data.define(method_: {wire: 'method', fixed: 'emulation.setTouchOverride'}, params: {wire: 'params', ref: 'Emulation::SetTouchOverrideParameters'}); end

          class SetTouchOverrideParameters < Data.define(max_touch_points: {wire: 'maxTouchPoints', nullable: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class SetGeolocationOverrideParameters_Coordinates < Data.define(contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}, coordinates: {wire: 'coordinates', nullable: true, ref: 'Emulation::GeolocationCoordinates'}); end

          class SetGeolocationOverrideParameters_Error < Data.define(contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}, error: {wire: 'error', ref: 'Emulation::GeolocationPositionError'}); end

          def initialize(bidi)
            @bidi = bidi
          end

          def set_forced_colors_mode_theme_override(theme:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setForcedColorsModeThemeOverride', theme: theme, contexts: contexts, userContexts: user_contexts)
          end

          def set_geolocation_override(contexts: nil, user_contexts: nil, coordinates: nil, error: nil)
            @bidi.send_cmd('emulation.setGeolocationOverride', contexts: contexts, userContexts: user_contexts, coordinates: coordinates, error: error)
          end

          def set_locale_override(locale:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setLocaleOverride', locale: locale, contexts: contexts, userContexts: user_contexts)
          end

          def set_network_conditions(network_conditions:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setNetworkConditions', networkConditions: network_conditions, contexts: contexts, userContexts: user_contexts)
          end

          def set_screen_orientation_override(screen_orientation:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setScreenOrientationOverride', screenOrientation: screen_orientation, contexts: contexts, userContexts: user_contexts)
          end

          def set_screen_settings_override(screen_area:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setScreenSettingsOverride', screenArea: screen_area, contexts: contexts, userContexts: user_contexts)
          end

          def set_scripting_enabled(enabled:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setScriptingEnabled', enabled: enabled, contexts: contexts, userContexts: user_contexts)
          end

          def set_scrollbar_type_override(scrollbar_type:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setScrollbarTypeOverride', scrollbarType: scrollbar_type, contexts: contexts, userContexts: user_contexts)
          end

          def set_timezone_override(timezone:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setTimezoneOverride', timezone: timezone, contexts: contexts, userContexts: user_contexts)
          end

          def set_touch_override(max_touch_points:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setTouchOverride', maxTouchPoints: max_touch_points, contexts: contexts, userContexts: user_contexts)
          end

          def set_user_agent_override(user_agent:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('emulation.setUserAgentOverride', userAgent: user_agent, contexts: contexts, userContexts: user_contexts)
          end

        end # Emulation
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
