# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: input

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Input
          EVENTS = {
            file_dialog_opened: 'input.fileDialogOpened',
          }.freeze

          POINTER_TYPE = {
            mouse: 'mouse',
            pen: 'pen',
            touch: 'touch',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

          def perform_actions(context:, actions:)
            @bidi.send_cmd('input.performActions', context: context, actions: actions)
          end

          def release_actions(context:)
            @bidi.send_cmd('input.releaseActions', context: context)
          end

          def set_files(context:, element:, files:)
            @bidi.send_cmd('input.setFiles', context: context, element: element, files: files)
          end

        end # Input
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
