# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: input

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Input
          EVENTS = {
            file_dialog_opened: 'input.fileDialogOpened',
          }.freeze

          POINTER_TYPE = {
            mouse: 'mouse',
            pen: 'pen',
            touch: 'touch',
          }.freeze

          class ElementOrigin < Data.define(type: {fixed: 'element'}, element: {wire: 'element', ref: 'Script::SharedReference'}); end

          class PerformActions < Data.define(method_: {wire: 'method', fixed: 'input.performActions'}, params: {wire: 'params', ref: 'Input::PerformActionsParameters'}); end

          class PerformActionsParameters < Data.define(context: 'context', actions: {wire: 'actions', ref: 'Input::SourceActions', list: true}); end

          class SourceActions < Union
            discriminator 'type'
            variants(
              'none' => 'Input::NoneSourceActions',
              'key' => 'Input::KeySourceActions',
              'pointer' => 'Input::PointerSourceActions',
              'wheel' => 'Input::WheelSourceActions',
            )
          end

          class NoneSourceActions < Data.define(type: {fixed: 'none'}, id: 'id', actions: {wire: 'actions', ref: 'Input::PauseAction', list: true}); end

          class KeySourceActions < Data.define(type: {fixed: 'key'}, id: 'id', actions: {wire: 'actions', ref: 'Input::KeySourceAction', list: true}); end

          class KeySourceAction < Union
            discriminator 'type'
            variants(
              'pause' => 'Input::PauseAction',
              'keyDown' => 'Input::KeyDownAction',
              'keyUp' => 'Input::KeyUpAction',
            )
          end

          class PointerSourceActions < Data.define(type: {fixed: 'pointer'}, id: 'id', parameters: {wire: 'parameters', ref: 'Input::PointerParameters'}, actions: {wire: 'actions', ref: 'Input::PointerSourceAction', list: true}); end

          class PointerParameters < Data.define(pointer_type: 'pointerType'); end

          class PointerSourceAction < Union
            discriminator 'type'
            variants(
              'pause' => 'Input::PauseAction',
              'pointerDown' => 'Input::PointerDownAction',
              'pointerUp' => 'Input::PointerUpAction',
              'pointerMove' => 'Input::PointerMoveAction',
            )
          end

          class WheelSourceActions < Data.define(type: {fixed: 'wheel'}, id: 'id', actions: {wire: 'actions', ref: 'Input::WheelSourceAction', list: true}); end

          class WheelSourceAction < Union
            discriminator 'type'
            variants(
              'pause' => 'Input::PauseAction',
              'scroll' => 'Input::WheelScrollAction',
            )
          end

          class PauseAction < Data.define(type: {fixed: 'pause'}, duration: 'duration'); end

          class KeyDownAction < Data.define(type: {fixed: 'keyDown'}, value: 'value'); end

          class KeyUpAction < Data.define(type: {fixed: 'keyUp'}, value: 'value'); end

          class PointerUpAction < Data.define(type: {fixed: 'pointerUp'}, button: 'button'); end

          class PointerDownAction < Data.define(type: {fixed: 'pointerDown'}, button: 'button', width: 'width', height: 'height', pressure: 'pressure', tangential_pressure: 'tangentialPressure', twist: 'twist', altitude_angle: 'altitudeAngle', azimuth_angle: 'azimuthAngle'); end

          class PointerMoveAction < Data.define(type: {fixed: 'pointerMove'}, x: 'x', y: 'y', duration: 'duration', origin: {wire: 'origin', ref: 'Input::Origin'}, width: 'width', height: 'height', pressure: 'pressure', tangential_pressure: 'tangentialPressure', twist: 'twist', altitude_angle: 'altitudeAngle', azimuth_angle: 'azimuthAngle'); end

          class WheelScrollAction < Data.define(type: {fixed: 'scroll'}, x: 'x', y: 'y', delta_x: 'deltaX', delta_y: 'deltaY', duration: 'duration', origin: {wire: 'origin', ref: 'Input::Origin'}); end

          class PointerCommonProperties < Data.define(width: 'width', height: 'height', pressure: 'pressure', tangential_pressure: 'tangentialPressure', twist: 'twist', altitude_angle: 'altitudeAngle', azimuth_angle: 'azimuthAngle'); end

          class Origin < Union
            discriminator 'type'
            variants(
              'element' => 'Input::ElementOrigin',
            )
          end

          class ReleaseActions < Data.define(method_: {wire: 'method', fixed: 'input.releaseActions'}, params: {wire: 'params', ref: 'Input::ReleaseActionsParameters'}); end

          class ReleaseActionsParameters < Data.define(context: 'context'); end

          class SetFiles < Data.define(method_: {wire: 'method', fixed: 'input.setFiles'}, params: {wire: 'params', ref: 'Input::SetFilesParameters'}); end

          class SetFilesParameters < Data.define(context: 'context', element: {wire: 'element', ref: 'Script::SharedReference'}, files: {wire: 'files', list: true}); end

          class FileDialogOpened < Data.define(method_: {wire: 'method', fixed: 'input.fileDialogOpened'}, params: {wire: 'params', ref: 'Input::FileDialogInfo'}); end

          class FileDialogInfo < Data.define(context: 'context', user_context: 'userContext', element: {wire: 'element', ref: 'Script::SharedReference'}, multiple: 'multiple'); end

          def initialize(bidi)
            @bidi = bidi
          end

          def perform_actions(context:, actions:)
            @bidi.send_cmd('input.performActions', context: context, actions: actions)
          end

          def release_actions(context:)
            @bidi.send_cmd('input.releaseActions', context: context)
          end

          def set_files(context:, element:, files:)
            @bidi.send_cmd('input.setFiles', context: context, element: element, files: files)
          end

        end # Input
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
