# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: log

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Log
          EVENTS = {
            entry_added: 'log.entryAdded',
          }.freeze

          LEVEL = {
            debug: 'debug',
            info: 'info',
            warn: 'warn',
            error: 'error',
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class Entry < Union
            discriminator 'type'
            variants(
              'console' => 'Log::ConsoleLogEntry',
              'javascript' => 'Log::JavascriptLogEntry',
            )
            fallback 'Log::GenericLogEntry'
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class BaseLogEntry < Data.define(level: {json_key: 'level', enum: 'Log::LEVEL'}, source: {json_key: 'source', ref: 'Script::Source'}, text: {json_key: 'text', nullable: true}, timestamp: 'timestamp', stack_trace: {json_key: 'stackTrace', ref: 'Script::StackTrace'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class GenericLogEntry < Data.define(level: {json_key: 'level', enum: 'Log::LEVEL'}, source: {json_key: 'source', ref: 'Script::Source'}, text: {json_key: 'text', nullable: true}, timestamp: 'timestamp', stack_trace: {json_key: 'stackTrace', ref: 'Script::StackTrace'}, type: 'type'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ConsoleLogEntry < Data.define(type: {fixed: 'console'}, level: {json_key: 'level', enum: 'Log::LEVEL'}, source: {json_key: 'source', ref: 'Script::Source'}, text: {json_key: 'text', nullable: true}, timestamp: 'timestamp', stack_trace: {json_key: 'stackTrace', ref: 'Script::StackTrace'}, method_: 'method', args: {json_key: 'args', ref: 'Script::RemoteValue', list: true}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class JavascriptLogEntry < Data.define(type: {fixed: 'javascript'}, level: {json_key: 'level', enum: 'Log::LEVEL'}, source: {json_key: 'source', ref: 'Script::Source'}, text: {json_key: 'text', nullable: true}, timestamp: 'timestamp', stack_trace: {json_key: 'stackTrace', ref: 'Script::StackTrace'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class EntryAdded < Data.define(method_: {json_key: 'method', fixed: 'log.entryAdded'}, params: {json_key: 'params', ref: 'Log::Entry'}); end

          def initialize(context)
            @transport = Transport.for(context)
          end

        end # Log
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
