# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: log

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Log
          EVENTS = {
            entry_added: 'log.entryAdded',
          }.freeze

          LEVEL = {
            debug: 'debug',
            info: 'info',
            warn: 'warn',
            error: 'error',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

        end # Log
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
