# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: network

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Network
          EVENTS = {
            auth_required: 'network.authRequired',
            before_request_sent: 'network.beforeRequestSent',
            fetch_error: 'network.fetchError',
            response_completed: 'network.responseCompleted',
            response_started: 'network.responseStarted',
          }.freeze

          COLLECTOR_TYPE = {
            blob: 'blob',
          }.freeze

          SAME_SITE = {
            strict: 'strict',
            lax: 'lax',
            none: 'none',
            default: 'default',
          }.freeze

          DATA_TYPE = {
            request: 'request',
            response: 'response',
          }.freeze

          INTERCEPT_PHASE = {
            before_request_sent: 'beforeRequestSent',
            response_started: 'responseStarted',
            auth_required: 'authRequired',
          }.freeze

          INITIATOR_TYPE = {
            parser: 'parser',
            script: 'script',
            preflight: 'preflight',
            other: 'other',
          }.freeze

          CONTINUE_WITH_AUTH_NO_CREDENTIALS_ACTION = {
            default: 'default',
            cancel: 'cancel',
          }.freeze

          SET_CACHE_BEHAVIOR_PARAMETERS_CACHE_BEHAVIOR = {
            default: 'default',
            bypass: 'bypass',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

          def add_data_collector(data_types:, max_encoded_data_size:, collector_type: nil, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('network.addDataCollector', dataTypes: data_types, maxEncodedDataSize: max_encoded_data_size, collectorType: collector_type, contexts: contexts, userContexts: user_contexts)
          end

          def add_intercept(phases:, contexts: nil, url_patterns: nil)
            @bidi.send_cmd('network.addIntercept', phases: phases, contexts: contexts, urlPatterns: url_patterns)
          end

          def continue_request(request:, body: nil, cookies: nil, headers: nil, method: nil, url: nil)
            @bidi.send_cmd('network.continueRequest', request: request, body: body, cookies: cookies, headers: headers, method: method, url: url)
          end

          def continue_response(request:, cookies: nil, credentials: nil, headers: nil, reason_phrase: nil, status_code: nil)
            @bidi.send_cmd('network.continueResponse', request: request, cookies: cookies, credentials: credentials, headers: headers, reasonPhrase: reason_phrase, statusCode: status_code)
          end

          def continue_with_auth(request:, action:, credentials: nil)
            @bidi.send_cmd('network.continueWithAuth', request: request, action: action, credentials: credentials)
          end

          def disown_data(data_type:, collector:, request:)
            @bidi.send_cmd('network.disownData', dataType: data_type, collector: collector, request: request)
          end

          def fail_request(request:)
            @bidi.send_cmd('network.failRequest', request: request)
          end

          def get_data(data_type:, request:, collector: nil, disown: nil)
            @bidi.send_cmd('network.getData', dataType: data_type, collector: collector, disown: disown, request: request)
          end

          def provide_response(request:, body: nil, cookies: nil, headers: nil, reason_phrase: nil, status_code: nil)
            @bidi.send_cmd('network.provideResponse', request: request, body: body, cookies: cookies, headers: headers, reasonPhrase: reason_phrase, statusCode: status_code)
          end

          def remove_data_collector(collector:)
            @bidi.send_cmd('network.removeDataCollector', collector: collector)
          end

          def remove_intercept(intercept:)
            @bidi.send_cmd('network.removeIntercept', intercept: intercept)
          end

          def set_cache_behavior(cache_behavior:, contexts: nil)
            @bidi.send_cmd('network.setCacheBehavior', cacheBehavior: cache_behavior, contexts: contexts)
          end

          def set_extra_headers(headers:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('network.setExtraHeaders', headers: headers, contexts: contexts, userContexts: user_contexts)
          end

        end # Network
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
