# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: permissions

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Permissions
          PERMISSION_STATE = {
            granted: 'granted',
            denied: 'denied',
            prompt: 'prompt',
          }.freeze

          class PermissionDescriptor < Data.define(name: 'name'); end

          class SetPermission < Data.define(method_: {json_key: 'method', fixed: 'permissions.setPermission'}, params: {json_key: 'params', ref: 'Permissions::SetPermissionParameters'}); end

          class SetPermissionParameters < Data.define(descriptor: {json_key: 'descriptor', ref: 'Permissions::PermissionDescriptor'}, state: 'state', origin: 'origin', embedded_origin: 'embeddedOrigin', user_context: 'userContext'); end

          def initialize(transport)
            @transport = transport
          end

          def set_permission(descriptor:, state:, origin:, embedded_origin: nil, user_context: nil)
            @transport.execute('permissions.setPermission', {descriptor: descriptor, state: state, origin: origin, embeddedOrigin: embedded_origin, userContext: user_context})
          end

        end # Permissions
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
