# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: permissions

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Permissions
          PERMISSION_STATE = {
            granted: 'granted',
            denied: 'denied',
            prompt: 'prompt',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

          def set_permission(descriptor:, state:, origin:, embedded_origin: nil, user_context: nil)
            @bidi.send_cmd('permissions.setPermission', descriptor: descriptor, state: state, origin: origin, embeddedOrigin: embedded_origin, userContext: user_context)
          end

        end # Permissions
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
