# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: script

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Script
          EVENTS = {
            message: 'script.message',
            realm_created: 'script.realmCreated',
            realm_destroyed: 'script.realmDestroyed',
          }.freeze

          SPECIAL_NUMBER = {
            na_n: 'NaN',
            neg_0: '-0',
            infinity: 'Infinity',
            neg_infinity: '-Infinity',
          }.freeze

          REALM_TYPE = {
            window: 'window',
            dedicated_worker: 'dedicated-worker',
            shared_worker: 'shared-worker',
            service_worker: 'service-worker',
            worker: 'worker',
            paint_worklet: 'paint-worklet',
            audio_worklet: 'audio-worklet',
            worklet: 'worklet',
          }.freeze

          RESULT_OWNERSHIP = {
            root: 'root',
            none: 'none',
          }.freeze

          NODE_PROPERTIES_MODE = {
            open: 'open',
            closed: 'closed',
          }.freeze

          SERIALIZATION_OPTIONS_INCLUDE_SHADOW_TREE = {
            none: 'none',
            open: 'open',
            all: 'all',
          }.freeze

          class ChannelValue < Data.define(type: {fixed: 'channel'}, value: {json_key: 'value', ref: 'Script::ChannelProperties'}); end

          class ChannelProperties < Data.define(channel: 'channel', serialization_options: {json_key: 'serializationOptions', ref: 'Script::SerializationOptions'}, ownership: 'ownership'); end

          class EvaluateResult < Union
            discriminator 'type'
            variants(
              'success' => 'Script::EvaluateResultSuccess',
              'exception' => 'Script::EvaluateResultException',
            )
          end

          class EvaluateResultSuccess < Data.define(type: {fixed: 'success'}, result: {json_key: 'result', ref: 'Script::RemoteValue'}, realm: 'realm'); end

          class EvaluateResultException < Data.define(type: {fixed: 'exception'}, exception_details: {json_key: 'exceptionDetails', ref: 'Script::ExceptionDetails'}, realm: 'realm'); end

          class ExceptionDetails < Data.define(column_number: 'columnNumber', exception: {json_key: 'exception', ref: 'Script::RemoteValue'}, line_number: 'lineNumber', stack_trace: {json_key: 'stackTrace', ref: 'Script::StackTrace'}, text: 'text'); end

          class LocalValue < Union
            discriminator 'type'
            variants(
              'undefined' => 'Script::UndefinedValue',
              'null' => 'Script::NullValue',
              'string' => 'Script::StringValue',
              'number' => 'Script::NumberValue',
              'boolean' => 'Script::BooleanValue',
              'bigint' => 'Script::BigIntValue',
              'channel' => 'Script::ChannelValue',
              'array' => 'Script::ArrayLocalValue',
              'date' => 'Script::DateLocalValue',
              'map' => 'Script::MapLocalValue',
              'object' => 'Script::ObjectLocalValue',
              'regexp' => 'Script::RegExpLocalValue',
              'set' => 'Script::SetLocalValue',
            )
            fallback 'Script::RemoteReference'
          end

          class ArrayLocalValue < Data.define(type: {fixed: 'array'}, value: {json_key: 'value', ref: 'Script::LocalValue', list: true}); end

          class DateLocalValue < Data.define(type: {fixed: 'date'}, value: 'value'); end

          class MapLocalValue < Data.define(type: {fixed: 'map'}, value: {json_key: 'value', list: true}); end

          class ObjectLocalValue < Data.define(type: {fixed: 'object'}, value: {json_key: 'value', list: true}); end

          class RegExpValue < Data.define(pattern: 'pattern', flags: 'flags'); end

          class RegExpLocalValue < Data.define(type: {fixed: 'regexp'}, value: {json_key: 'value', ref: 'Script::RegExpValue'}); end

          class SetLocalValue < Data.define(type: {fixed: 'set'}, value: {json_key: 'value', ref: 'Script::LocalValue', list: true}); end

          class PrimitiveProtocolValue < Union
            discriminator 'type'
            variants(
              'undefined' => 'Script::UndefinedValue',
              'null' => 'Script::NullValue',
              'string' => 'Script::StringValue',
              'number' => 'Script::NumberValue',
              'boolean' => 'Script::BooleanValue',
              'bigint' => 'Script::BigIntValue',
            )
          end

          class UndefinedValue < Data.define(type: {fixed: 'undefined'}); end

          class NullValue < Data.define(type: {fixed: 'null'}); end

          class StringValue < Data.define(type: {fixed: 'string'}, value: 'value'); end

          class NumberValue < Data.define(type: {fixed: 'number'}, value: 'value'); end

          class BooleanValue < Data.define(type: {fixed: 'boolean'}, value: 'value'); end

          class BigIntValue < Data.define(type: {fixed: 'bigint'}, value: 'value'); end

          class RealmInfo < Union
            discriminator 'type'
            variants(
              'window' => 'Script::WindowRealmInfo',
              'dedicated-worker' => 'Script::DedicatedWorkerRealmInfo',
              'shared-worker' => 'Script::SharedWorkerRealmInfo',
              'service-worker' => 'Script::ServiceWorkerRealmInfo',
              'worker' => 'Script::WorkerRealmInfo',
              'paint-worklet' => 'Script::PaintWorkletRealmInfo',
              'audio-worklet' => 'Script::AudioWorkletRealmInfo',
              'worklet' => 'Script::WorkletRealmInfo',
            )
          end

          class BaseRealmInfo < Data.define(realm: 'realm', origin: 'origin'); end

          class WindowRealmInfo < Data.define(type: {fixed: 'window'}, realm: 'realm', origin: 'origin', context: 'context', user_context: 'userContext', sandbox: 'sandbox'); end

          class DedicatedWorkerRealmInfo < Data.define(type: {fixed: 'dedicated-worker'}, realm: 'realm', origin: 'origin', owners: {json_key: 'owners', list: true}); end

          class SharedWorkerRealmInfo < Data.define(type: {fixed: 'shared-worker'}, realm: 'realm', origin: 'origin'); end

          class ServiceWorkerRealmInfo < Data.define(type: {fixed: 'service-worker'}, realm: 'realm', origin: 'origin'); end

          class WorkerRealmInfo < Data.define(type: {fixed: 'worker'}, realm: 'realm', origin: 'origin'); end

          class PaintWorkletRealmInfo < Data.define(type: {fixed: 'paint-worklet'}, realm: 'realm', origin: 'origin'); end

          class AudioWorkletRealmInfo < Data.define(type: {fixed: 'audio-worklet'}, realm: 'realm', origin: 'origin'); end

          class WorkletRealmInfo < Data.define(type: {fixed: 'worklet'}, realm: 'realm', origin: 'origin'); end

          class RemoteReference < Union
            presence(
              'Script::SharedReference' => ['sharedId'],
              'Script::RemoteObjectReference' => ['handle'],
            )
          end

          class SharedReference < Data.define(shared_id: 'sharedId', handle: 'handle', extensible: true); end

          class RemoteObjectReference < Data.define(handle: 'handle', shared_id: 'sharedId', extensible: true); end

          class RemoteValue < Union
            discriminator 'type'
            variants(
              'undefined' => 'Script::UndefinedValue',
              'null' => 'Script::NullValue',
              'string' => 'Script::StringValue',
              'number' => 'Script::NumberValue',
              'boolean' => 'Script::BooleanValue',
              'bigint' => 'Script::BigIntValue',
              'symbol' => 'Script::SymbolRemoteValue',
              'array' => 'Script::ArrayRemoteValue',
              'object' => 'Script::ObjectRemoteValue',
              'function' => 'Script::FunctionRemoteValue',
              'regexp' => 'Script::RegExpRemoteValue',
              'date' => 'Script::DateRemoteValue',
              'map' => 'Script::MapRemoteValue',
              'set' => 'Script::SetRemoteValue',
              'weakmap' => 'Script::WeakMapRemoteValue',
              'weakset' => 'Script::WeakSetRemoteValue',
              'generator' => 'Script::GeneratorRemoteValue',
              'error' => 'Script::ErrorRemoteValue',
              'proxy' => 'Script::ProxyRemoteValue',
              'promise' => 'Script::PromiseRemoteValue',
              'typedarray' => 'Script::TypedArrayRemoteValue',
              'arraybuffer' => 'Script::ArrayBufferRemoteValue',
              'nodelist' => 'Script::NodeListRemoteValue',
              'htmlcollection' => 'Script::HTMLCollectionRemoteValue',
              'node' => 'Script::NodeRemoteValue',
              'window' => 'Script::WindowProxyRemoteValue',
            )
          end

          class SymbolRemoteValue < Data.define(type: {fixed: 'symbol'}, handle: 'handle', internal_id: 'internalId'); end

          class ArrayRemoteValue < Data.define(type: {fixed: 'array'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', ref: 'Script::RemoteValue', list: true}); end

          class ObjectRemoteValue < Data.define(type: {fixed: 'object'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', list: true}); end

          class FunctionRemoteValue < Data.define(type: {fixed: 'function'}, handle: 'handle', internal_id: 'internalId'); end

          class RegExpRemoteValue < Data.define(type: {fixed: 'regexp'}, value: {json_key: 'value', ref: 'Script::RegExpValue'}, handle: 'handle', internal_id: 'internalId'); end

          class DateRemoteValue < Data.define(type: {fixed: 'date'}, value: 'value', handle: 'handle', internal_id: 'internalId'); end

          class MapRemoteValue < Data.define(type: {fixed: 'map'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', list: true}); end

          class SetRemoteValue < Data.define(type: {fixed: 'set'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', ref: 'Script::RemoteValue', list: true}); end

          class WeakMapRemoteValue < Data.define(type: {fixed: 'weakmap'}, handle: 'handle', internal_id: 'internalId'); end

          class WeakSetRemoteValue < Data.define(type: {fixed: 'weakset'}, handle: 'handle', internal_id: 'internalId'); end

          class GeneratorRemoteValue < Data.define(type: {fixed: 'generator'}, handle: 'handle', internal_id: 'internalId'); end

          class ErrorRemoteValue < Data.define(type: {fixed: 'error'}, handle: 'handle', internal_id: 'internalId'); end

          class ProxyRemoteValue < Data.define(type: {fixed: 'proxy'}, handle: 'handle', internal_id: 'internalId'); end

          class PromiseRemoteValue < Data.define(type: {fixed: 'promise'}, handle: 'handle', internal_id: 'internalId'); end

          class TypedArrayRemoteValue < Data.define(type: {fixed: 'typedarray'}, handle: 'handle', internal_id: 'internalId'); end

          class ArrayBufferRemoteValue < Data.define(type: {fixed: 'arraybuffer'}, handle: 'handle', internal_id: 'internalId'); end

          class NodeListRemoteValue < Data.define(type: {fixed: 'nodelist'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', ref: 'Script::RemoteValue', list: true}); end

          class HTMLCollectionRemoteValue < Data.define(type: {fixed: 'htmlcollection'}, handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', ref: 'Script::RemoteValue', list: true}); end

          class NodeRemoteValue < Data.define(type: {fixed: 'node'}, shared_id: 'sharedId', handle: 'handle', internal_id: 'internalId', value: {json_key: 'value', ref: 'Script::NodeProperties'}); end

          class NodeProperties < Data.define(node_type: 'nodeType', child_node_count: 'childNodeCount', attributes: 'attributes', children: {json_key: 'children', ref: 'Script::NodeRemoteValue', list: true}, local_name: 'localName', mode: 'mode', namespace_uri: 'namespaceURI', node_value: 'nodeValue', shadow_root: {json_key: 'shadowRoot', nullable: true, ref: 'Script::NodeRemoteValue'}); end

          class WindowProxyRemoteValue < Data.define(type: {fixed: 'window'}, value: {json_key: 'value', ref: 'Script::WindowProxyProperties'}, handle: 'handle', internal_id: 'internalId'); end

          class WindowProxyProperties < Data.define(context: 'context'); end

          class SerializationOptions < Data.define(max_dom_depth: {json_key: 'maxDomDepth', nullable: true}, max_object_depth: {json_key: 'maxObjectDepth', nullable: true}, include_shadow_tree: 'includeShadowTree'); end

          class StackFrame < Data.define(column_number: 'columnNumber', function_name: 'functionName', line_number: 'lineNumber', url: 'url'); end

          class StackTrace < Data.define(call_frames: {json_key: 'callFrames', ref: 'Script::StackFrame', list: true}); end

          class Source < Data.define(realm: 'realm', context: 'context', user_context: 'userContext'); end

          class RealmTarget < Data.define(realm: 'realm'); end

          class ContextTarget < Data.define(context: 'context', sandbox: 'sandbox'); end

          class Target < Union
            presence(
              'Script::ContextTarget' => ['context'],
              'Script::RealmTarget' => ['realm'],
            )
          end

          class AddPreloadScript < Data.define(method_: {json_key: 'method', fixed: 'script.addPreloadScript'}, params: {json_key: 'params', ref: 'Script::AddPreloadScriptParameters'}); end

          class AddPreloadScriptParameters < Data.define(function_declaration: 'functionDeclaration', arguments: {json_key: 'arguments', ref: 'Script::ChannelValue', list: true}, contexts: {json_key: 'contexts', list: true}, user_contexts: {json_key: 'userContexts', list: true}, sandbox: 'sandbox'); end

          class AddPreloadScriptResult < Data.define(script: 'script'); end

          class Disown < Data.define(method_: {json_key: 'method', fixed: 'script.disown'}, params: {json_key: 'params', ref: 'Script::DisownParameters'}); end

          class DisownParameters < Data.define(handles: {json_key: 'handles', list: true}, target: {json_key: 'target', ref: 'Script::Target'}); end

          class CallFunction < Data.define(method_: {json_key: 'method', fixed: 'script.callFunction'}, params: {json_key: 'params', ref: 'Script::CallFunctionParameters'}); end

          class CallFunctionParameters < Data.define(function_declaration: 'functionDeclaration', await_promise: 'awaitPromise', target: {json_key: 'target', ref: 'Script::Target'}, arguments: {json_key: 'arguments', ref: 'Script::LocalValue', list: true}, result_ownership: 'resultOwnership', serialization_options: {json_key: 'serializationOptions', ref: 'Script::SerializationOptions'}, this: {json_key: 'this', ref: 'Script::LocalValue'}, user_activation: 'userActivation'); end

          class Evaluate < Data.define(method_: {json_key: 'method', fixed: 'script.evaluate'}, params: {json_key: 'params', ref: 'Script::EvaluateParameters'}); end

          class EvaluateParameters < Data.define(expression: 'expression', target: {json_key: 'target', ref: 'Script::Target'}, await_promise: 'awaitPromise', result_ownership: 'resultOwnership', serialization_options: {json_key: 'serializationOptions', ref: 'Script::SerializationOptions'}, user_activation: 'userActivation'); end

          class GetRealms < Data.define(method_: {json_key: 'method', fixed: 'script.getRealms'}, params: {json_key: 'params', ref: 'Script::GetRealmsParameters'}); end

          class GetRealmsParameters < Data.define(context: 'context', type: 'type'); end

          class GetRealmsResult < Data.define(realms: {json_key: 'realms', ref: 'Script::RealmInfo', list: true}); end

          class RemovePreloadScript < Data.define(method_: {json_key: 'method', fixed: 'script.removePreloadScript'}, params: {json_key: 'params', ref: 'Script::RemovePreloadScriptParameters'}); end

          class RemovePreloadScriptParameters < Data.define(script: 'script'); end

          class Message < Data.define(method_: {json_key: 'method', fixed: 'script.message'}, params: {json_key: 'params', ref: 'Script::MessageParameters'}); end

          class MessageParameters < Data.define(channel: 'channel', data: {json_key: 'data', ref: 'Script::RemoteValue'}, source: {json_key: 'source', ref: 'Script::Source'}); end

          class RealmCreated < Data.define(method_: {json_key: 'method', fixed: 'script.realmCreated'}, params: {json_key: 'params', ref: 'Script::RealmInfo'}); end

          class RealmDestroyed < Data.define(method_: {json_key: 'method', fixed: 'script.realmDestroyed'}, params: {json_key: 'params', ref: 'Script::RealmDestroyedParameters'}); end

          class RealmDestroyedParameters < Data.define(realm: 'realm'); end

          def initialize(context)
            @transport = Transport.for(context)
          end

          def add_preload_script(function_declaration:, arguments: UNSET, contexts: UNSET, user_contexts: UNSET, sandbox: UNSET)
            @transport.execute('script.addPreloadScript', AddPreloadScriptParameters.new(function_declaration: function_declaration, arguments: arguments, contexts: contexts, user_contexts: user_contexts, sandbox: sandbox), Protocol.const_get('Script::AddPreloadScriptResult'))
          end

          def call_function(function_declaration:, await_promise:, target:, arguments: UNSET, result_ownership: UNSET, serialization_options: UNSET, this: UNSET, user_activation: UNSET)
            Enum.check!('resultOwnership', result_ownership, Script::RESULT_OWNERSHIP)
            @transport.execute('script.callFunction', CallFunctionParameters.new(function_declaration: function_declaration, await_promise: await_promise, target: target, arguments: arguments, result_ownership: result_ownership, serialization_options: serialization_options, this: this, user_activation: user_activation), Protocol.const_get('Script::EvaluateResult'))
          end

          def disown(handles:, target:)
            @transport.execute('script.disown', DisownParameters.new(handles: handles, target: target))
          end

          def evaluate(expression:, target:, await_promise:, result_ownership: UNSET, serialization_options: UNSET, user_activation: UNSET)
            Enum.check!('resultOwnership', result_ownership, Script::RESULT_OWNERSHIP)
            @transport.execute('script.evaluate', EvaluateParameters.new(expression: expression, target: target, await_promise: await_promise, result_ownership: result_ownership, serialization_options: serialization_options, user_activation: user_activation), Protocol.const_get('Script::EvaluateResult'))
          end

          def get_realms(context: UNSET, type: UNSET)
            Enum.check!('type', type, Script::REALM_TYPE)
            @transport.execute('script.getRealms', GetRealmsParameters.new(context: context, type: type), Protocol.const_get('Script::GetRealmsResult'))
          end

          def remove_preload_script(script:)
            @transport.execute('script.removePreloadScript', RemovePreloadScriptParameters.new(script: script))
          end

        end # Script
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
