# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: session

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Session
          USER_PROMPT_HANDLER_TYPE = {
            accept: 'accept',
            dismiss: 'dismiss',
            ignore: 'ignore',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

          def end_
            @bidi.send_cmd('session.end')
          end

          def new(capabilities:)
            @bidi.send_cmd('session.new', capabilities: capabilities)
          end

          def status
            @bidi.send_cmd('session.status')
          end

          def subscribe(events:, contexts: nil, user_contexts: nil)
            @bidi.send_cmd('session.subscribe', events: events, contexts: contexts, userContexts: user_contexts)
          end

          def unsubscribe(events: nil, subscriptions: nil)
            @bidi.send_cmd('session.unsubscribe', events: events, subscriptions: subscriptions)
          end

        end # Session
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
