# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: session

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Session
          USER_PROMPT_HANDLER_TYPE = {
            accept: 'accept',
            dismiss: 'dismiss',
            ignore: 'ignore',
          }.freeze

          class CapabilitiesRequest < Data.define(always_match: {wire: 'alwaysMatch', ref: 'Session::CapabilityRequest'}, first_match: {wire: 'firstMatch', ref: 'Session::CapabilityRequest', list: true}); end

          class CapabilityRequest < Data.define(accept_insecure_certs: 'acceptInsecureCerts', browser_name: 'browserName', browser_version: 'browserVersion', platform_name: 'platformName', proxy: {wire: 'proxy', ref: 'Session::ProxyConfiguration'}, unhandled_prompt_behavior: {wire: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'}, extensible: true); end

          class ProxyConfiguration < Union
            discriminator 'proxyType'
            variants(
              'autodetect' => 'Session::AutodetectProxyConfiguration',
              'direct' => 'Session::DirectProxyConfiguration',
              'manual' => 'Session::ManualProxyConfiguration',
              'pac' => 'Session::PacProxyConfiguration',
              'system' => 'Session::SystemProxyConfiguration',
            )
          end

          class AutodetectProxyConfiguration < Data.define(proxy_type: {wire: 'proxyType', fixed: 'autodetect'}, extensible: true); end

          class DirectProxyConfiguration < Data.define(proxy_type: {wire: 'proxyType', fixed: 'direct'}, extensible: true); end

          class ManualProxyConfiguration < Data.define(proxy_type: {wire: 'proxyType', fixed: 'manual'}, http_proxy: 'httpProxy', ssl_proxy: 'sslProxy', socks_proxy: 'socksProxy', socks_version: 'socksVersion', no_proxy: {wire: 'noProxy', list: true}, extensible: true); end

          class SocksProxyConfiguration < Data.define(socks_proxy: 'socksProxy', socks_version: 'socksVersion'); end

          class PacProxyConfiguration < Data.define(proxy_type: {wire: 'proxyType', fixed: 'pac'}, proxy_autoconfig_url: 'proxyAutoconfigUrl', extensible: true); end

          class SystemProxyConfiguration < Data.define(proxy_type: {wire: 'proxyType', fixed: 'system'}, extensible: true); end

          class UserPromptHandler < Data.define(alert: 'alert', before_unload: 'beforeUnload', confirm: 'confirm', default: 'default', file: 'file', prompt: 'prompt'); end

          class SubscribeParameters < Data.define(events: {wire: 'events', list: true}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          class UnsubscribeByIDRequest < Data.define(subscriptions: {wire: 'subscriptions', list: true}); end

          class UnsubscribeByAttributesRequest < Data.define(events: {wire: 'events', list: true}); end

          class Status < Data.define(method_: {wire: 'method', fixed: 'session.status'}, params: 'params'); end

          class StatusResult < Data.define(ready: 'ready', message: 'message'); end

          class New < Data.define(method_: {wire: 'method', fixed: 'session.new'}, params: {wire: 'params', ref: 'Session::NewParameters'}); end

          class NewParameters < Data.define(capabilities: {wire: 'capabilities', ref: 'Session::CapabilitiesRequest'}); end

          class NewResult < Data.define(session_id: 'sessionId', capabilities: {wire: 'capabilities', ref: 'Session::NewResultCapabilities'}); end

          class End < Data.define(method_: {wire: 'method', fixed: 'session.end'}, params: 'params'); end

          class Subscribe < Data.define(method_: {wire: 'method', fixed: 'session.subscribe'}, params: {wire: 'params', ref: 'Session::SubscribeParameters'}); end

          class SubscribeResult < Data.define(subscription: 'subscription'); end

          class Unsubscribe < Data.define(method_: {wire: 'method', fixed: 'session.unsubscribe'}, params: {wire: 'params', ref: 'Session::UnsubscribeParameters'}); end

          class UnsubscribeParameters < Union
            presence(
              'Session::UnsubscribeByAttributesRequest' => ['events'],
              'Session::UnsubscribeByIDRequest' => ['subscriptions'],
            )
          end

          class NewResultCapabilities < Data.define(accept_insecure_certs: 'acceptInsecureCerts', browser_name: 'browserName', browser_version: 'browserVersion', platform_name: 'platformName', set_window_rect: 'setWindowRect', user_agent: 'userAgent', proxy: {wire: 'proxy', ref: 'Session::ProxyConfiguration'}, unhandled_prompt_behavior: {wire: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'}, web_socket_url: 'webSocketUrl', extensible: true); end

          def initialize(bidi)
            @bidi = bidi
          end

          def end_
            @bidi.send_cmd('session.end')
          end

          def new(capabilities:)
            result = @bidi.send_cmd('session.new', capabilities: capabilities)
            Protocol.const_get('Session::NewResult').from_json(result)
          end

          def status
            result = @bidi.send_cmd('session.status')
            Protocol.const_get('Session::StatusResult').from_json(result)
          end

          def subscribe(events:, contexts: nil, user_contexts: nil)
            result = @bidi.send_cmd('session.subscribe', events: events, contexts: contexts, userContexts: user_contexts)
            Protocol.const_get('Session::SubscribeResult').from_json(result)
          end

          def unsubscribe(events: nil, subscriptions: nil)
            @bidi.send_cmd('session.unsubscribe', events: events, subscriptions: subscriptions)
          end

        end # Session
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
