# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: speculation

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Speculation
          EVENTS = {
            prefetch_status_updated: 'speculation.prefetchStatusUpdated',
          }.freeze

          PRELOADING_STATUS = {
            pending: 'pending',
            ready: 'ready',
            success: 'success',
            failure: 'failure',
          }.freeze

          def initialize(bidi)
            @bidi = bidi
          end

        end # Speculation
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
