# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: speculation

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class Speculation
          EVENTS = {
            prefetch_status_updated: 'speculation.prefetchStatusUpdated',
          }.freeze

          PRELOADING_STATUS = {
            pending: 'pending',
            ready: 'ready',
            success: 'success',
            failure: 'failure',
          }.freeze

          class PrefetchStatusUpdated < ::Data.define(:params)
            include Serializable
            discriminator wire: 'method', value: 'speculation.prefetchStatusUpdated'
            field :params, wire: 'params', required: true, ref: 'Speculation::PrefetchStatusUpdatedParameters'
          end

          class PrefetchStatusUpdatedParameters < ::Data.define(:context, :url, :status)
            include Serializable
            field :context, wire: 'context', required: true
            field :url, wire: 'url', required: true
            field :status, wire: 'status', required: true
          end

          def initialize(bidi)
            @bidi = bidi
          end

        end # Speculation
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
