# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: userAgentClientHints

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class UserAgentClientHints
          class SetClientHintsOverrideCommand < Data.define(method_: {wire: 'method', fixed: 'userAgentClientHints.setClientHintsOverride'}, params: {wire: 'params', ref: 'UserAgentClientHints::SetClientHintsOverrideCommandParams'}); end

          class ClientHintsMetadata < Data.define(brands: {wire: 'brands', ref: 'UserAgentClientHints::BrandVersion', list: true}, full_version_list: {wire: 'fullVersionList', ref: 'UserAgentClientHints::BrandVersion', list: true}, platform: 'platform', platform_version: 'platformVersion', architecture: 'architecture', model: 'model', mobile: 'mobile', bitness: 'bitness', wow64: 'wow64', form_factors: {wire: 'formFactors', list: true}); end

          class BrandVersion < Data.define(brand: 'brand', version: 'version'); end

          class SetClientHintsOverrideCommandParams < Data.define(client_hints: {wire: 'clientHints', nullable: true, ref: 'UserAgentClientHints::ClientHintsMetadata'}, contexts: {wire: 'contexts', list: true}, user_contexts: {wire: 'userContexts', list: true}); end

          def initialize(bidi)
            @bidi = bidi
          end

          def set_client_hints_override
            @bidi.send_cmd('userAgentClientHints.setClientHintsOverride')
          end

        end # UserAgentClientHints
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
