# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: userAgentClientHints

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class UserAgentClientHints
          class SetClientHintsOverrideCommand < Data.define(method_: {json_key: 'method', fixed: 'userAgentClientHints.setClientHintsOverride'}, params: {json_key: 'params', ref: 'UserAgentClientHints::SetClientHintsOverrideCommand::Params'})
            class Params < Data.define(client_hints: {json_key: 'clientHints', nullable: true, ref: 'UserAgentClientHints::ClientHintsMetadata'}, contexts: {json_key: 'contexts', list: true}, user_contexts: {json_key: 'userContexts', list: true}); end
          end

          class ClientHintsMetadata < Data.define(brands: {json_key: 'brands', ref: 'UserAgentClientHints::BrandVersion', list: true}, full_version_list: {json_key: 'fullVersionList', ref: 'UserAgentClientHints::BrandVersion', list: true}, platform: 'platform', platform_version: 'platformVersion', architecture: 'architecture', model: 'model', mobile: 'mobile', bitness: 'bitness', wow64: 'wow64', form_factors: {json_key: 'formFactors', list: true}); end

          class BrandVersion < Data.define(brand: 'brand', version: 'version'); end

          def initialize(transport)
            @transport = transport
          end

          def set_client_hints_override
            @transport.execute('userAgentClientHints.setClientHintsOverride')
          end

        end # UserAgentClientHints
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
