# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: userAgentClientHints

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class UserAgentClientHints
          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class SetClientHintsOverrideCommand < Data.define(method_: {json_key: 'method', fixed: 'userAgentClientHints.setClientHintsOverride'}, params: {json_key: 'params', ref: 'UserAgentClientHints::SetClientHintsOverrideCommand::Params'})
            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            class Params < Data.define(client_hints: {json_key: 'clientHints', nullable: true, ref: 'UserAgentClientHints::ClientHintsMetadata'}, contexts: {json_key: 'contexts', list: true}, user_contexts: {json_key: 'userContexts', list: true}); end
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ClientHintsMetadata < Data.define(brands: {json_key: 'brands', ref: 'UserAgentClientHints::BrandVersion', list: true}, full_version_list: {json_key: 'fullVersionList', ref: 'UserAgentClientHints::BrandVersion', list: true}, platform: 'platform', platform_version: 'platformVersion', architecture: 'architecture', model: 'model', mobile: 'mobile', bitness: 'bitness', wow64: 'wow64', form_factors: {json_key: 'formFactors', list: true}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class BrandVersion < Data.define(brand: 'brand', version: 'version'); end

          def initialize(context)
            @transport = Transport.for(context)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_client_hints_override
            @transport.execute(cmd: 'userAgentClientHints.setClientHintsOverride')
          end

        end # UserAgentClientHints
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
