# frozen_string_literal: true

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: webExtension

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        class WebExtension
          class Install < Data.define(method_: {json_key: 'method', fixed: 'webExtension.install'}, params: {json_key: 'params', ref: 'WebExtension::InstallParameters'}); end

          class InstallParameters < Data.define(extension_data: {json_key: 'extensionData', ref: 'WebExtension::ExtensionData'}); end

          class ExtensionData < Union
            discriminator 'type'
            variants(
              'archivePath' => 'WebExtension::ExtensionArchivePath',
              'base64' => 'WebExtension::ExtensionBase64Encoded',
              'path' => 'WebExtension::ExtensionPath',
            )
          end

          class ExtensionPath < Data.define(type: {fixed: 'path'}, path: 'path'); end

          class ExtensionArchivePath < Data.define(type: {fixed: 'archivePath'}, path: 'path'); end

          class ExtensionBase64Encoded < Data.define(type: {fixed: 'base64'}, value: 'value'); end

          class InstallResult < Data.define(extension: 'extension'); end

          class Uninstall < Data.define(method_: {json_key: 'method', fixed: 'webExtension.uninstall'}, params: {json_key: 'params', ref: 'WebExtension::UninstallParameters'}); end

          class UninstallParameters < Data.define(extension: 'extension'); end

          def initialize(transport)
            @transport = transport
          end

          def install(extension_data:)
            @transport.execute('webExtension.install', {extensionData: extension_data}, returns: Protocol.const_get('WebExtension::InstallResult'))
          end

          def uninstall(extension:)
            @transport.execute('webExtension.uninstall', {extension: extension})
          end

        end # WebExtension
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
