# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Generated from the WebDriver BiDi specification.
# WebDriver BiDi module: webExtension

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class WebExtension
          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class Install < Data.define(method_: {json_key: 'method', fixed: 'webExtension.install'}, params: {json_key: 'params', ref: 'WebExtension::InstallParameters'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class InstallParameters < Data.define(extension_data: {json_key: 'extensionData', ref: 'WebExtension::ExtensionData'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ExtensionData < Union
            discriminator 'type'
            variants(
              'archivePath' => 'WebExtension::ExtensionArchivePath',
              'base64' => 'WebExtension::ExtensionBase64Encoded',
              'path' => 'WebExtension::ExtensionPath',
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ExtensionPath < Data.define(type: {fixed: 'path'}, path: 'path'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ExtensionArchivePath < Data.define(type: {fixed: 'archivePath'}, path: 'path'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ExtensionBase64Encoded < Data.define(type: {fixed: 'base64'}, value: 'value'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class InstallResult < Data.define(extension: 'extension'); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class Uninstall < Data.define(method_: {json_key: 'method', fixed: 'webExtension.uninstall'}, params: {json_key: 'params', ref: 'WebExtension::UninstallParameters'}); end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class UninstallParameters < Data.define(extension: 'extension'); end

          def initialize(context)
            @transport = Transport.for(context)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def install(extension_data:)
            @transport.execute(cmd: 'webExtension.install', params: InstallParameters.new(extension_data: extension_data), result: WebExtension::InstallResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def uninstall(extension:)
            @transport.execute(cmd: 'webExtension.uninstall', params: UninstallParameters.new(extension: extension))
          end

        end # WebExtension
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
