inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

Style/DotPosition:
  EnforcedStyle: trailing

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Alias:
  EnforcedStyle: prefer_alias_method


Style/ConditionalAssignment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/FileName:
  Enabled: false