inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/DotPosition:
  EnforcedStyle: trailing

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'

Style/DoubleNegation:
  Exclude:
    - 'lib/selenium/webdriver/common/platform.rb'
    - 'lib/selenium/webdriver/safari/options.rb'

# Can't disable just for blocks
Lint/UnusedMethodArgument:
  Enabled: false

Style/ZeroLengthPredicate:
  Exclude:
    - 'lib/selenium/webdriver/common/html5/shared_web_storage.rb'

Style/Semicolon:
  Exclude:
    - 'spec/unit/selenium/webdriver/file_reaper_spec.rb'

Style/NumericLiterals:
  MinDigits: 10
