# Configuration for Java CI
# To force the execution of this workflow, add [run java] to your commit message
name: 'CI - Dotnet'

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  check_workflow:
    permissions:
      contents: none
    uses: ./.github/workflows/should-workflow-run.yml
    with:
      bazel-target-prefix: '//dotnet'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run unit tests
        uses: ./.github/actions/bazel
        with:
          command: build //dotnet/src/webdriver:package

  browser_tests:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-${{ matrix.browser }}-tests-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-${{ matrix.browser }}-tests-
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Chrome and ChromeDriver
        uses: ./.github/actions/setup-chrome
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Run browser tests in Chrome
      - run: dotnet test
        env:
          DISPLAY: :99

