name: CI - Rust

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean
        default: false
      branch:
        required: false
        type: string
        default: trunk
    secrets:
      SELENIUM_CI_TOKEN:
        required: false
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
    with:
      name: Tests (${{ matrix.os }})
      os: ${{ matrix.os }}
      run: >
        bazel test
        --pin_browsers=false
        --test_env=SE_FORCE_BROWSER_DOWNLOAD=true
        --test_env=SE_SKIP_DRIVER_IN_PATH=true
        --test_env=RUST_BACKTRACE=full
        --test_env=RUST_TEST_NOCAPTURE=1
        --flaky_test_attempts=3
        //rust/...
        //rb/spec/integration/selenium/webdriver:driver_finder-firefox
