name: Pin Browsers
on:
  workflow_dispatch:

jobs:
  update:
    name: Update Pinned Browsers
    uses: ./.github/workflows/bazel.yml
    with:
      name: Pin Browsers
      cache-key: pin-browsers
      run: bazel run //scripts:pinned_browsers
