name: Release Staging

on:
  pull_request:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-packages:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release-preparation-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=$(echo $BRANCH_NAME | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build and Stage Packages
        run: ./go all:package
      - name: Prep git
        run: |
          git config --local user.email "selenium-ci@users.noreply.github.com"
          git config --local user.name "Selenium CI Bot"
      - name: Tag Release
        run: |
          git tag selenium-${{ env.VERSION }}
          git push origin selenium-${{ env.VERSION }}
      - name: Update Nightly Tag to Remove pre-release
        run: |
          git fetch --tags
          git tag -d nightly || echo "Nightly tag not found"
          git tag nightly
          git push origin nightly
      - name: Generate Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: Selenium ${{ env.VERSION }}
          body: |
            ### Changelogs

            For each component's detailed changelog, please check:
            * [Ruby](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/CHANGES)
            * [Python](https://github.com/SeleniumHQ/selenium/blob/trunk/py/CHANGES)
            * [JavaScript](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/CHANGES.md)
            * [Java](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG)
            * [DotNet](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/CHANGELOG)
            * [IEDriverServer](https://github.com/SeleniumHQ/selenium/blob/trunk/cpp/iedriverserver/CHANGELOG)

          tag_name: selenium-${{ env.VERSION }}
          draft: true
          generate_release_notes: true
          prerelease: false
          files: build/dist/*.*
      - name: Update Documentation
        run: ./go all:docs
      - name: Documentation Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SELENIUM_CI_TOKEN }}
          author: Selenium CI Bot <selenium-ci@users.noreply.github.com>
          delete-branch: true
          branch: api-docs-${{ env.VERSION }}
          base: gh-pages
          title: Update documentation for Selenium ${{ env.VERSION }}
          body: |
            This PR updates the api documentation for all bindings
            based on the latest released version

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: documentation
          draft: false
